const HSK_DATA = [
// ===== HSK 1 (150 words) =====
{hz:"你",py:"nǐ",kr:"너",lv:1,tp:"대명사",ex:[{cn:"你好！",py:"Nǐ hǎo!",kr:"안녕!"}]},
{hz:"好",py:"hǎo",kr:"좋다",lv:1,tp:"형용사",ex:[{cn:"你好吗？",py:"Nǐ hǎo ma?",kr:"잘 지내?"}]},
{hz:"我",py:"wǒ",kr:"나",lv:1,tp:"대명사",ex:[{cn:"我是学生。",py:"Wǒ shì xuéshēng.",kr:"나는 학생이다."}]},
{hz:"是",py:"shì",kr:"~이다",lv:1,tp:"동사",ex:[{cn:"他是老师。",py:"Tā shì lǎoshī.",kr:"그는 선생님이다."}]},
{hz:"的",py:"de",kr:"~의",lv:1,tp:"조사",ex:[{cn:"我的书。",py:"Wǒ de shū.",kr:"나의 책."}]},
{hz:"了",py:"le",kr:"~했다(완료)",lv:1,tp:"조사",ex:[{cn:"我吃了。",py:"Wǒ chī le.",kr:"나는 먹었다."}]},
{hz:"在",py:"zài",kr:"~에 있다",lv:1,tp:"동사",ex:[{cn:"我在家。",py:"Wǒ zài jiā.",kr:"나는 집에 있다."}]},
{hz:"他",py:"tā",kr:"그",lv:1,tp:"대명사",ex:[{cn:"他很高。",py:"Tā hěn gāo.",kr:"그는 키가 크다."}]},
{hz:"她",py:"tā",kr:"그녀",lv:1,tp:"대명사",ex:[{cn:"她是我妈妈。",py:"Tā shì wǒ māma.",kr:"그녀는 나의 엄마다."}]},
{hz:"们",py:"men",kr:"~들(복수)",lv:1,tp:"접미사",ex:[{cn:"我们是朋友。",py:"Wǒmen shì péngyǒu.",kr:"우리는 친구다."}]},
{hz:"这",py:"zhè",kr:"이것",lv:1,tp:"대명사",ex:[{cn:"这是什么？",py:"Zhè shì shénme?",kr:"이것은 무엇입니까?"}]},
{hz:"那",py:"nà",kr:"저것",lv:1,tp:"대명사",ex:[{cn:"那是我的。",py:"Nà shì wǒ de.",kr:"저것은 나의 것이다."}]},
{hz:"什么",py:"shénme",kr:"무엇",lv:1,tp:"대명사",ex:[{cn:"你叫什么？",py:"Nǐ jiào shénme?",kr:"이름이 뭐야?"}]},
{hz:"谁",py:"shéi",kr:"누구",lv:1,tp:"대명사",ex:[{cn:"他是谁？",py:"Tā shì shéi?",kr:"그는 누구야?"}]},
{hz:"哪",py:"nǎ",kr:"어디/어느",lv:1,tp:"대명사",ex:[{cn:"你去哪？",py:"Nǐ qù nǎ?",kr:"어디 가니?"}]},
{hz:"哪儿",py:"nǎr",kr:"어디",lv:1,tp:"대명사",ex:[{cn:"你住哪儿？",py:"Nǐ zhù nǎr?",kr:"어디에 살아?"}]},
{hz:"几",py:"jǐ",kr:"몇",lv:1,tp:"대명사",ex:[{cn:"几点了？",py:"Jǐ diǎn le?",kr:"몇 시야?"}]},
{hz:"多",py:"duō",kr:"많다",lv:1,tp:"형용사",ex:[{cn:"人很多。",py:"Rén hěn duō.",kr:"사람이 많다."}]},
{hz:"少",py:"shǎo",kr:"적다",lv:1,tp:"형용사",ex:[{cn:"人很少。",py:"Rén hěn shǎo.",kr:"사람이 적다."}]},
{hz:"大",py:"dà",kr:"크다",lv:1,tp:"형용사",ex:[{cn:"很大。",py:"Hěn dà.",kr:"매우 크다."}]},
{hz:"小",py:"xiǎo",kr:"작다",lv:1,tp:"형용사",ex:[{cn:"太小了。",py:"Tài xiǎo le.",kr:"너무 작다."}]},
{hz:"多少",py:"duōshǎo",kr:"얼마",lv:1,tp:"대명사",ex:[{cn:"多少钱？",py:"Duōshǎo qián?",kr:"얼마예요?"}]},
{hz:"一",py:"yī",kr:"일, 하나",lv:1,tp:"수사",ex:[{cn:"一个人。",py:"Yī gè rén.",kr:"한 사람."}]},
{hz:"二",py:"èr",kr:"이, 둘",lv:1,tp:"수사",ex:[{cn:"二月。",py:"Èr yuè.",kr:"2월."}]},
{hz:"三",py:"sān",kr:"삼, 셋",lv:1,tp:"수사",ex:[{cn:"三个。",py:"Sān gè.",kr:"세 개."}]},
{hz:"四",py:"sì",kr:"사, 넷",lv:1,tp:"수사",ex:[{cn:"四月。",py:"Sì yuè.",kr:"4월."}]},
{hz:"五",py:"wǔ",kr:"오, 다섯",lv:1,tp:"수사",ex:[{cn:"五块钱。",py:"Wǔ kuài qián.",kr:"5위안."}]},
{hz:"六",py:"liù",kr:"육, 여섯",lv:1,tp:"수사",ex:[{cn:"六个月。",py:"Liù gè yuè.",kr:"6개월."}]},
{hz:"七",py:"qī",kr:"칠, 일곱",lv:1,tp:"수사",ex:[{cn:"七天。",py:"Qī tiān.",kr:"7일."}]},
{hz:"八",py:"bā",kr:"팔, 여덟",lv:1,tp:"수사",ex:[{cn:"八点。",py:"Bā diǎn.",kr:"8시."}]},
{hz:"九",py:"jiǔ",kr:"구, 아홉",lv:1,tp:"수사",ex:[{cn:"九月。",py:"Jiǔ yuè.",kr:"9월."}]},
{hz:"十",py:"shí",kr:"십, 열",lv:1,tp:"수사",ex:[{cn:"十个人。",py:"Shí gè rén.",kr:"10명."}]},
{hz:"零",py:"líng",kr:"영, 제로",lv:1,tp:"수사",ex:[{cn:"零度。",py:"Líng dù.",kr:"영도."}]},
{hz:"两",py:"liǎng",kr:"둘, 두",lv:1,tp:"수사",ex:[{cn:"两个人。",py:"Liǎng gè rén.",kr:"두 사람."}]},
{hz:"百",py:"bǎi",kr:"백",lv:1,tp:"수사",ex:[{cn:"一百块。",py:"Yī bǎi kuài.",kr:"100위안."}]},
{hz:"不",py:"bù",kr:"아니다, ~않다",lv:1,tp:"부사",ex:[{cn:"我不去。",py:"Wǒ bù qù.",kr:"나는 안 간다."}]},
{hz:"没",py:"méi",kr:"없다, ~않았다",lv:1,tp:"부사",ex:[{cn:"没有。",py:"Méiyǒu.",kr:"없다."}]},
{hz:"没有",py:"méiyǒu",kr:"없다, ~한 적 없다",lv:1,tp:"동사",ex:[{cn:"我没有钱。",py:"Wǒ méiyǒu qián.",kr:"나는 돈이 없다."}]},
{hz:"很",py:"hěn",kr:"매우",lv:1,tp:"부사",ex:[{cn:"很好。",py:"Hěn hǎo.",kr:"매우 좋다."}]},
{hz:"太",py:"tài",kr:"너무",lv:1,tp:"부사",ex:[{cn:"太贵了。",py:"Tài guì le.",kr:"너무 비싸다."}]},
{hz:"都",py:"dōu",kr:"모두",lv:1,tp:"부사",ex:[{cn:"都很好。",py:"Dōu hěn hǎo.",kr:"모두 좋다."}]},
{hz:"和",py:"hé",kr:"~와, 그리고",lv:1,tp:"접속사",ex:[{cn:"你和我。",py:"Nǐ hé wǒ.",kr:"너와 나."}]},
{hz:"人",py:"rén",kr:"사람",lv:1,tp:"명사",ex:[{cn:"中国人。",py:"Zhōngguó rén.",kr:"중국 사람."}]},
{hz:"家",py:"jiā",kr:"집, 가정",lv:1,tp:"명사",ex:[{cn:"回家。",py:"Huí jiā.",kr:"집에 돌아가다."}]},
{hz:"学生",py:"xuéshēng",kr:"학생",lv:1,tp:"명사",ex:[{cn:"我是学生。",py:"Wǒ shì xuéshēng.",kr:"나는 학생이다."}]},
{hz:"老师",py:"lǎoshī",kr:"선생님",lv:1,tp:"명사",ex:[{cn:"王老师好。",py:"Wáng lǎoshī hǎo.",kr:"왕 선생님 안녕하세요."}]},
{hz:"同学",py:"tóngxué",kr:"반 친구, 학우",lv:1,tp:"명사",ex:[{cn:"我的同学。",py:"Wǒ de tóngxué.",kr:"나의 반 친구."}]},
{hz:"朋友",py:"péngyǒu",kr:"친구",lv:1,tp:"명사",ex:[{cn:"好朋友。",py:"Hǎo péngyǒu.",kr:"좋은 친구."}]},
{hz:"爸爸",py:"bàba",kr:"아빠",lv:1,tp:"명사",ex:[{cn:"我爸爸。",py:"Wǒ bàba.",kr:"우리 아빠."}]},
{hz:"妈妈",py:"māma",kr:"엄마",lv:1,tp:"명사",ex:[{cn:"我妈妈。",py:"Wǒ māma.",kr:"우리 엄마."}]},
{hz:"儿子",py:"érzi",kr:"아들",lv:1,tp:"명사",ex:[{cn:"他的儿子。",py:"Tā de érzi.",kr:"그의 아들."}]},
{hz:"女儿",py:"nǚ'ér",kr:"딸",lv:1,tp:"명사",ex:[{cn:"她的女儿。",py:"Tā de nǚ'ér.",kr:"그녀의 딸."}]},
{hz:"先生",py:"xiānshēng",kr:"선생님, ~씨(남)",lv:1,tp:"명사",ex:[{cn:"王先生。",py:"Wáng xiānshēng.",kr:"왕 선생님."}]},
{hz:"小姐",py:"xiǎojiě",kr:"아가씨",lv:1,tp:"명사",ex:[{cn:"李小姐。",py:"Lǐ xiǎojiě.",kr:"이 아가씨."}]},
{hz:"医生",py:"yīshēng",kr:"의사",lv:1,tp:"명사",ex:[{cn:"看医生。",py:"Kàn yīshēng.",kr:"병원에 가다."}]},
{hz:"水",py:"shuǐ",kr:"물",lv:1,tp:"명사",ex:[{cn:"喝水。",py:"Hē shuǐ.",kr:"물을 마시다."}]},
{hz:"饭",py:"fàn",kr:"밥",lv:1,tp:"명사",ex:[{cn:"吃饭。",py:"Chī fàn.",kr:"밥을 먹다."}]},
{hz:"菜",py:"cài",kr:"요리, 채소",lv:1,tp:"명사",ex:[{cn:"中国菜。",py:"Zhōngguó cài.",kr:"중국 요리."}]},
{hz:"米饭",py:"mǐfàn",kr:"쌀밥",lv:1,tp:"명사",ex:[{cn:"吃米饭。",py:"Chī mǐfàn.",kr:"쌀밥을 먹다."}]},
{hz:"水果",py:"shuǐguǒ",kr:"과일",lv:1,tp:"명사",ex:[{cn:"吃水果。",py:"Chī shuǐguǒ.",kr:"과일을 먹다."}]},
{hz:"苹果",py:"píngguǒ",kr:"사과",lv:1,tp:"명사",ex:[{cn:"吃苹果。",py:"Chī píngguǒ.",kr:"사과를 먹다."}]},
{hz:"茶",py:"chá",kr:"차",lv:1,tp:"명사",ex:[{cn:"喝茶。",py:"Hē chá.",kr:"차를 마시다."}]},
{hz:"杯子",py:"bēizi",kr:"컵",lv:1,tp:"명사",ex:[{cn:"一个杯子。",py:"Yī gè bēizi.",kr:"컵 하나."}]},
{hz:"书",py:"shū",kr:"책",lv:1,tp:"명사",ex:[{cn:"看书。",py:"Kàn shū.",kr:"책을 보다."}]},
{hz:"钱",py:"qián",kr:"돈",lv:1,tp:"명사",ex:[{cn:"有钱。",py:"Yǒu qián.",kr:"돈이 있다."}]},
{hz:"东西",py:"dōngxī",kr:"물건",lv:1,tp:"명사",ex:[{cn:"买东西。",py:"Mǎi dōngxī.",kr:"물건을 사다."}]},
{hz:"天",py:"tiān",kr:"하늘, 날",lv:1,tp:"명사",ex:[{cn:"今天。",py:"Jīntiān.",kr:"오늘."}]},
{hz:"年",py:"nián",kr:"해, 년",lv:1,tp:"명사",ex:[{cn:"今年。",py:"Jīnnián.",kr:"올해."}]},
{hz:"月",py:"yuè",kr:"달, 월",lv:1,tp:"명사",ex:[{cn:"一月。",py:"Yī yuè.",kr:"1월."}]},
{hz:"日",py:"rì",kr:"일, 날",lv:1,tp:"명사",ex:[{cn:"生日。",py:"Shēngrì.",kr:"생일."}]},
{hz:"星期",py:"xīngqī",kr:"요일, 주",lv:1,tp:"명사",ex:[{cn:"星期一。",py:"Xīngqī yī.",kr:"월요일."}]},
{hz:"点",py:"diǎn",kr:"시(시간), 점",lv:1,tp:"명사",ex:[{cn:"三点了。",py:"Sān diǎn le.",kr:"3시다."}]},
{hz:"分钟",py:"fēnzhōng",kr:"분(시간)",lv:1,tp:"명사",ex:[{cn:"五分钟。",py:"Wǔ fēnzhōng.",kr:"5분."}]},
{hz:"今天",py:"jīntiān",kr:"오늘",lv:1,tp:"명사",ex:[{cn:"今天很热。",py:"Jīntiān hěn rè.",kr:"오늘 매우 덥다."}]},
{hz:"明天",py:"míngtiān",kr:"내일",lv:1,tp:"명사",ex:[{cn:"明天见。",py:"Míngtiān jiàn.",kr:"내일 만나."}]},
{hz:"昨天",py:"zuótiān",kr:"어제",lv:1,tp:"명사",ex:[{cn:"昨天下雨了。",py:"Zuótiān xià yǔ le.",kr:"어제 비가 왔다."}]},
{hz:"上午",py:"shàngwǔ",kr:"오전",lv:1,tp:"명사",ex:[{cn:"上午好。",py:"Shàngwǔ hǎo.",kr:"좋은 아침."}]},
{hz:"下午",py:"xiàwǔ",kr:"오후",lv:1,tp:"명사",ex:[{cn:"下午三点。",py:"Xiàwǔ sān diǎn.",kr:"오후 3시."}]},
{hz:"时候",py:"shíhòu",kr:"때, 시간",lv:1,tp:"명사",ex:[{cn:"什么时候？",py:"Shénme shíhòu?",kr:"언제?"}]},
{hz:"现在",py:"xiànzài",kr:"지금",lv:1,tp:"명사",ex:[{cn:"现在几点？",py:"Xiànzài jǐ diǎn?",kr:"지금 몇 시?"}]},
{hz:"中国",py:"Zhōngguó",kr:"중국",lv:1,tp:"명사",ex:[{cn:"我去中国。",py:"Wǒ qù Zhōngguó.",kr:"나는 중국에 간다."}]},
{hz:"北京",py:"Běijīng",kr:"베이징",lv:1,tp:"명사",ex:[{cn:"去北京。",py:"Qù Běijīng.",kr:"베이징에 가다."}]},
{hz:"汉语",py:"hànyǔ",kr:"중국어",lv:1,tp:"명사",ex:[{cn:"学汉语。",py:"Xué hànyǔ.",kr:"중국어를 배우다."}]},
{hz:"字",py:"zì",kr:"글자",lv:1,tp:"명사",ex:[{cn:"写字。",py:"Xiě zì.",kr:"글자를 쓰다."}]},
{hz:"名字",py:"míngzì",kr:"이름",lv:1,tp:"명사",ex:[{cn:"你的名字。",py:"Nǐ de míngzì.",kr:"너의 이름."}]},
{hz:"桌子",py:"zhuōzi",kr:"책상, 탁자",lv:1,tp:"명사",ex:[{cn:"在桌子上。",py:"Zài zhuōzi shàng.",kr:"탁자 위에."}]},
{hz:"椅子",py:"yǐzi",kr:"의자",lv:1,tp:"명사",ex:[{cn:"坐椅子。",py:"Zuò yǐzi.",kr:"의자에 앉다."}]},
{hz:"衣服",py:"yīfú",kr:"옷",lv:1,tp:"명사",ex:[{cn:"穿衣服。",py:"Chuān yīfú.",kr:"옷을 입다."}]},
{hz:"天气",py:"tiānqì",kr:"날씨",lv:1,tp:"명사",ex:[{cn:"天气很好。",py:"Tiānqì hěn hǎo.",kr:"날씨가 좋다."}]},
{hz:"雨",py:"yǔ",kr:"비",lv:1,tp:"명사",ex:[{cn:"下雨了。",py:"Xià yǔ le.",kr:"비가 온다."}]},
{hz:"电影",py:"diànyǐng",kr:"영화",lv:1,tp:"명사",ex:[{cn:"看电影。",py:"Kàn diànyǐng.",kr:"영화를 보다."}]},
{hz:"电脑",py:"diànnǎo",kr:"컴퓨터",lv:1,tp:"명사",ex:[{cn:"用电脑。",py:"Yòng diànnǎo.",kr:"컴퓨터를 사용하다."}]},
{hz:"电视",py:"diànshì",kr:"텔레비전",lv:1,tp:"명사",ex:[{cn:"看电视。",py:"Kàn diànshì.",kr:"TV를 보다."}]},
{hz:"医院",py:"yīyuàn",kr:"병원",lv:1,tp:"명사",ex:[{cn:"去医院。",py:"Qù yīyuàn.",kr:"병원에 가다."}]},
{hz:"学校",py:"xuéxiào",kr:"학교",lv:1,tp:"명사",ex:[{cn:"在学校。",py:"Zài xuéxiào.",kr:"학교에 있다."}]},
{hz:"商店",py:"shāngdiàn",kr:"상점",lv:1,tp:"명사",ex:[{cn:"去商店。",py:"Qù shāngdiàn.",kr:"상점에 가다."}]},
{hz:"饭店",py:"fàndiàn",kr:"식당, 호텔",lv:1,tp:"명사",ex:[{cn:"在饭店吃。",py:"Zài fàndiàn chī.",kr:"식당에서 먹다."}]},
{hz:"飞机",py:"fēijī",kr:"비행기",lv:1,tp:"명사",ex:[{cn:"坐飞机。",py:"Zuò fēijī.",kr:"비행기를 타다."}]},
{hz:"出租车",py:"chūzūchē",kr:"택시",lv:1,tp:"명사",ex:[{cn:"坐出租车。",py:"Zuò chūzūchē.",kr:"택시를 타다."}]},
{hz:"前面",py:"qiánmiàn",kr:"앞",lv:1,tp:"명사",ex:[{cn:"在前面。",py:"Zài qiánmiàn.",kr:"앞에 있다."}]},
{hz:"后面",py:"hòumiàn",kr:"뒤",lv:1,tp:"명사",ex:[{cn:"在后面。",py:"Zài hòumiàn.",kr:"뒤에 있다."}]},
{hz:"上",py:"shàng",kr:"위",lv:1,tp:"명사",ex:[{cn:"桌子上。",py:"Zhuōzi shàng.",kr:"탁자 위."}]},
{hz:"下",py:"xià",kr:"아래",lv:1,tp:"명사",ex:[{cn:"桌子下。",py:"Zhuōzi xià.",kr:"탁자 아래."}]},
{hz:"里",py:"lǐ",kr:"안, 속",lv:1,tp:"명사",ex:[{cn:"家里。",py:"Jiā lǐ.",kr:"집 안."}]},
{hz:"岁",py:"suì",kr:"살(나이)",lv:1,tp:"양사",ex:[{cn:"我二十岁。",py:"Wǒ èrshí suì.",kr:"나는 스무 살이다."}]},
{hz:"个",py:"gè",kr:"개(양사)",lv:1,tp:"양사",ex:[{cn:"一个人。",py:"Yī gè rén.",kr:"한 사람."}]},
{hz:"块",py:"kuài",kr:"위안(화폐)",lv:1,tp:"양사",ex:[{cn:"十块钱。",py:"Shí kuài qián.",kr:"10위안."}]},
{hz:"本",py:"běn",kr:"권(양사)",lv:1,tp:"양사",ex:[{cn:"一本书。",py:"Yī běn shū.",kr:"책 한 권."}]},
{hz:"些",py:"xiē",kr:"몇몇, 약간",lv:1,tp:"양사",ex:[{cn:"一些人。",py:"Yī xiē rén.",kr:"몇몇 사람."}]},
{hz:"去",py:"qù",kr:"가다",lv:1,tp:"동사",ex:[{cn:"去学校。",py:"Qù xuéxiào.",kr:"학교에 가다."}]},
{hz:"来",py:"lái",kr:"오다",lv:1,tp:"동사",ex:[{cn:"你来吗？",py:"Nǐ lái ma?",kr:"너 올 거야?"}]},
{hz:"回",py:"huí",kr:"돌아가다",lv:1,tp:"동사",ex:[{cn:"回家。",py:"Huí jiā.",kr:"집에 돌아가다."}]},
{hz:"吃",py:"chī",kr:"먹다",lv:1,tp:"동사",ex:[{cn:"吃苹果。",py:"Chī píngguǒ.",kr:"사과를 먹다."}]},
{hz:"喝",py:"hē",kr:"마시다",lv:1,tp:"동사",ex:[{cn:"喝咖啡。",py:"Hē kāfēi.",kr:"커피를 마시다."}]},
{hz:"看",py:"kàn",kr:"보다",lv:1,tp:"동사",ex:[{cn:"看书。",py:"Kàn shū.",kr:"책을 보다."}]},
{hz:"听",py:"tīng",kr:"듣다",lv:1,tp:"동사",ex:[{cn:"听音乐。",py:"Tīng yīnyuè.",kr:"음악을 듣다."}]},
{hz:"说",py:"shuō",kr:"말하다",lv:1,tp:"동사",ex:[{cn:"说中文。",py:"Shuō zhōngwén.",kr:"중국어를 말하다."}]},
{hz:"读",py:"dú",kr:"읽다",lv:1,tp:"동사",ex:[{cn:"读书。",py:"Dú shū.",kr:"책을 읽다."}]},
{hz:"写",py:"xiě",kr:"쓰다",lv:1,tp:"동사",ex:[{cn:"写汉字。",py:"Xiě hànzì.",kr:"한자를 쓰다."}]},
{hz:"学",py:"xué",kr:"배우다",lv:1,tp:"동사",ex:[{cn:"学中文。",py:"Xué zhōngwén.",kr:"중국어를 배우다."}]},
{hz:"学习",py:"xuéxí",kr:"공부하다",lv:1,tp:"동사",ex:[{cn:"学习汉语。",py:"Xuéxí hànyǔ.",kr:"중국어를 공부하다."}]},
{hz:"做",py:"zuò",kr:"하다, 만들다",lv:1,tp:"동사",ex:[{cn:"做作业。",py:"Zuò zuòyè.",kr:"숙제를 하다."}]},
{hz:"有",py:"yǒu",kr:"있다, 가지다",lv:1,tp:"동사",ex:[{cn:"我有钱。",py:"Wǒ yǒu qián.",kr:"나는 돈이 있다."}]},
{hz:"想",py:"xiǎng",kr:"생각하다, ~하고 싶다",lv:1,tp:"동사",ex:[{cn:"我想去。",py:"Wǒ xiǎng qù.",kr:"나는 가고 싶다."}]},
{hz:"会",py:"huì",kr:"~할 수 있다",lv:1,tp:"동사",ex:[{cn:"我会说。",py:"Wǒ huì shuō.",kr:"나는 말할 수 있다."}]},
{hz:"能",py:"néng",kr:"~할 수 있다",lv:1,tp:"동사",ex:[{cn:"你能来吗？",py:"Nǐ néng lái ma?",kr:"올 수 있어?"}]},
{hz:"叫",py:"jiào",kr:"부르다, ~라고 하다",lv:1,tp:"동사",ex:[{cn:"我叫小明。",py:"Wǒ jiào Xiǎo Míng.",kr:"나는 샤오밍이라고 한다."}]},
{hz:"住",py:"zhù",kr:"살다, 거주하다",lv:1,tp:"동사",ex:[{cn:"住在北京。",py:"Zhù zài Běijīng.",kr:"베이징에 살다."}]},
{hz:"买",py:"mǎi",kr:"사다",lv:1,tp:"동사",ex:[{cn:"买东西。",py:"Mǎi dōngxī.",kr:"물건을 사다."}]},
{hz:"开",py:"kāi",kr:"열다, 운전하다",lv:1,tp:"동사",ex:[{cn:"开门。",py:"Kāi mén.",kr:"문을 열다."}]},
{hz:"坐",py:"zuò",kr:"앉다, 타다",lv:1,tp:"동사",ex:[{cn:"请坐。",py:"Qǐng zuò.",kr:"앉으세요."}]},
{hz:"爱",py:"ài",kr:"사랑하다",lv:1,tp:"동사",ex:[{cn:"我爱你。",py:"Wǒ ài nǐ.",kr:"나는 너를 사랑한다."}]},
{hz:"喜欢",py:"xǐhuān",kr:"좋아하다",lv:1,tp:"동사",ex:[{cn:"我喜欢中国。",py:"Wǒ xǐhuān Zhōngguó.",kr:"나는 중국을 좋아한다."}]},
{hz:"工作",py:"gōngzuò",kr:"일하다, 일",lv:1,tp:"동사/명사",ex:[{cn:"我工作了。",py:"Wǒ gōngzuò le.",kr:"나는 일했다."}]},
{hz:"睡觉",py:"shuìjiào",kr:"자다",lv:1,tp:"동사",ex:[{cn:"我要睡觉。",py:"Wǒ yào shuìjiào.",kr:"나는 자려고 한다."}]},
{hz:"打电话",py:"dǎ diànhuà",kr:"전화하다",lv:1,tp:"동사",ex:[{cn:"给他打电话。",py:"Gěi tā dǎ diànhuà.",kr:"그에게 전화하다."}]},
{hz:"下雨",py:"xià yǔ",kr:"비가 오다",lv:1,tp:"동사",ex:[{cn:"今天下雨。",py:"Jīntiān xià yǔ.",kr:"오늘 비가 온다."}]},
{hz:"高兴",py:"gāoxìng",kr:"기쁘다",lv:1,tp:"형용사",ex:[{cn:"很高兴。",py:"Hěn gāoxìng.",kr:"매우 기쁘다."}]},
{hz:"漂亮",py:"piàoliang",kr:"예쁘다",lv:1,tp:"형용사",ex:[{cn:"她很漂亮。",py:"Tā hěn piàoliang.",kr:"그녀는 예쁘다."}]},
{hz:"热",py:"rè",kr:"덥다",lv:1,tp:"형용사",ex:[{cn:"今天很热。",py:"Jīntiān hěn rè.",kr:"오늘 매우 덥다."}]},
{hz:"冷",py:"lěng",kr:"춥다",lv:1,tp:"형용사",ex:[{cn:"天气很冷。",py:"Tiānqì hěn lěng.",kr:"날씨가 춥다."}]},
{hz:"对",py:"duì",kr:"맞다, ~에 대해",lv:1,tp:"형용사",ex:[{cn:"你说得对。",py:"Nǐ shuō de duì.",kr:"네 말이 맞아."}]},
{hz:"谢谢",py:"xièxiè",kr:"감사합니다",lv:1,tp:"동사",ex:[{cn:"谢谢你！",py:"Xièxiè nǐ!",kr:"감사합니다!"}]},
{hz:"不客气",py:"bú kèqì",kr:"천만에요",lv:1,tp:"관용어",ex:[{cn:"不客气！",py:"Bú kèqì!",kr:"천만에요!"}]},
{hz:"对不起",py:"duìbuqǐ",kr:"미안합니다",lv:1,tp:"관용어",ex:[{cn:"对不起！",py:"Duìbuqǐ!",kr:"미안합니다!"}]},
{hz:"再见",py:"zàijiàn",kr:"안녕(이별)",lv:1,tp:"관용어",ex:[{cn:"明天再见。",py:"Míngtiān zàijiàn.",kr:"내일 만나요."}]},
{hz:"请",py:"qǐng",kr:"~해 주세요",lv:1,tp:"동사",ex:[{cn:"请坐。",py:"Qǐng zuò.",kr:"앉으세요."}]},
{hz:"吗",py:"ma",kr:"~입니까?(의문)",lv:1,tp:"조사",ex:[{cn:"好吗？",py:"Hǎo ma?",kr:"좋아?"}]},
{hz:"呢",py:"ne",kr:"~은?(의문)",lv:1,tp:"조사",ex:[{cn:"你呢？",py:"Nǐ ne?",kr:"너는?"}]},
{hz:"怎么",py:"zěnme",kr:"어떻게",lv:1,tp:"대명사",ex:[{cn:"怎么走？",py:"Zěnme zǒu?",kr:"어떻게 가요?"}]},
{hz:"怎么样",py:"zěnmeyàng",kr:"어떻습니까",lv:1,tp:"대명사",ex:[{cn:"天气怎么样？",py:"Tiānqì zěnmeyàng?",kr:"날씨 어때요?"}]},

// ===== HSK 2 (150 words) =====
{hz:"因为",py:"yīnwèi",kr:"왜냐하면",lv:2,tp:"접속사",ex:[{cn:"因为下雨了。",py:"Yīnwèi xià yǔ le.",kr:"왜냐하면 비가 왔기 때문이다."}]},
{hz:"所以",py:"suǒyǐ",kr:"그래서",lv:2,tp:"접속사",ex:[{cn:"所以我不去。",py:"Suǒyǐ wǒ bù qù.",kr:"그래서 나는 안 간다."}]},
{hz:"但是",py:"dànshì",kr:"그러나",lv:2,tp:"접속사",ex:[{cn:"但是很贵。",py:"Dànshì hěn guì.",kr:"그러나 비싸다."}]},
{hz:"还是",py:"háishì",kr:"아니면, 여전히",lv:2,tp:"접속사",ex:[{cn:"茶还是咖啡？",py:"Chá háishì kāfēi?",kr:"차 아니면 커피?"}]},
{hz:"虽然",py:"suīrán",kr:"비록 ~이지만",lv:2,tp:"접속사",ex:[{cn:"虽然很累。",py:"Suīrán hěn lèi.",kr:"비록 피곤하지만."}]},
{hz:"已经",py:"yǐjīng",kr:"이미",lv:2,tp:"부사",ex:[{cn:"已经到了。",py:"Yǐjīng dào le.",kr:"이미 도착했다."}]},
{hz:"正在",py:"zhèngzài",kr:"~하는 중이다",lv:2,tp:"부사",ex:[{cn:"正在吃饭。",py:"Zhèngzài chī fàn.",kr:"밥 먹는 중이다."}]},
{hz:"一起",py:"yīqǐ",kr:"함께",lv:2,tp:"부사",ex:[{cn:"一起去吧。",py:"Yīqǐ qù ba.",kr:"같이 가자."}]},
{hz:"别",py:"bié",kr:"~하지 마",lv:2,tp:"부사",ex:[{cn:"别走。",py:"Bié zǒu.",kr:"가지 마."}]},
{hz:"还",py:"hái",kr:"아직, 또",lv:2,tp:"부사",ex:[{cn:"还有吗？",py:"Hái yǒu ma?",kr:"또 있어?"}]},
{hz:"再",py:"zài",kr:"다시",lv:2,tp:"부사",ex:[{cn:"再说一次。",py:"Zài shuō yī cì.",kr:"한 번 더 말해."}]},
{hz:"就",py:"jiù",kr:"바로, 곧",lv:2,tp:"부사",ex:[{cn:"我就来。",py:"Wǒ jiù lái.",kr:"곧 갈게."}]},
{hz:"才",py:"cái",kr:"겨우, 비로소",lv:2,tp:"부사",ex:[{cn:"他才来。",py:"Tā cái lái.",kr:"그가 이제야 왔다."}]},
{hz:"真",py:"zhēn",kr:"정말",lv:2,tp:"부사",ex:[{cn:"真好！",py:"Zhēn hǎo!",kr:"정말 좋다!"}]},
{hz:"最",py:"zuì",kr:"가장",lv:2,tp:"부사",ex:[{cn:"最好的。",py:"Zuì hǎo de.",kr:"가장 좋은."}]},
{hz:"也",py:"yě",kr:"~도",lv:2,tp:"부사",ex:[{cn:"我也去。",py:"Wǒ yě qù.",kr:"나도 간다."}]},
{hz:"又",py:"yòu",kr:"또",lv:2,tp:"부사",ex:[{cn:"又下雨了。",py:"Yòu xià yǔ le.",kr:"또 비가 온다."}]},
{hz:"快",py:"kuài",kr:"빠르다",lv:2,tp:"형용사",ex:[{cn:"太快了。",py:"Tài kuài le.",kr:"너무 빠르다."}]},
{hz:"慢",py:"màn",kr:"느리다",lv:2,tp:"형용사",ex:[{cn:"慢一点。",py:"Màn yīdiǎn.",kr:"좀 천천히."}]},
{hz:"新",py:"xīn",kr:"새롭다",lv:2,tp:"형용사",ex:[{cn:"新衣服。",py:"Xīn yīfú.",kr:"새 옷."}]},
{hz:"旧",py:"jiù",kr:"오래되다",lv:2,tp:"형용사",ex:[{cn:"旧书。",py:"Jiù shū.",kr:"오래된 책."}]},
{hz:"长",py:"cháng",kr:"길다",lv:2,tp:"형용사",ex:[{cn:"路很长。",py:"Lù hěn cháng.",kr:"길이 길다."}]},
{hz:"高",py:"gāo",kr:"높다, 키가 크다",lv:2,tp:"형용사",ex:[{cn:"他很高。",py:"Tā hěn gāo.",kr:"그는 키가 크다."}]},
{hz:"贵",py:"guì",kr:"비싸다",lv:2,tp:"형용사",ex:[{cn:"太贵了。",py:"Tài guì le.",kr:"너무 비싸다."}]},
{hz:"便宜",py:"piányi",kr:"싸다",lv:2,tp:"형용사",ex:[{cn:"很便宜。",py:"Hěn piányi.",kr:"매우 싸다."}]},
{hz:"远",py:"yuǎn",kr:"멀다",lv:2,tp:"형용사",ex:[{cn:"很远。",py:"Hěn yuǎn.",kr:"매우 멀다."}]},
{hz:"近",py:"jìn",kr:"가깝다",lv:2,tp:"형용사",ex:[{cn:"很近。",py:"Hěn jìn.",kr:"매우 가깝다."}]},
{hz:"白",py:"bái",kr:"하얗다",lv:2,tp:"형용사",ex:[{cn:"白色的。",py:"Bái sè de.",kr:"하얀색의."}]},
{hz:"黑",py:"hēi",kr:"검다",lv:2,tp:"형용사",ex:[{cn:"黑色的。",py:"Hēi sè de.",kr:"검은색의."}]},
{hz:"红",py:"hóng",kr:"빨갛다",lv:2,tp:"형용사",ex:[{cn:"红色。",py:"Hóng sè.",kr:"빨간색."}]},
{hz:"忙",py:"máng",kr:"바쁘다",lv:2,tp:"형용사",ex:[{cn:"我很忙。",py:"Wǒ hěn máng.",kr:"나는 바쁘다."}]},
{hz:"累",py:"lèi",kr:"피곤하다",lv:2,tp:"형용사",ex:[{cn:"很累。",py:"Hěn lèi.",kr:"피곤하다."}]},
{hz:"难",py:"nán",kr:"어렵다",lv:2,tp:"형용사",ex:[{cn:"很难。",py:"Hěn nán.",kr:"매우 어렵다."}]},
{hz:"容易",py:"róngyì",kr:"쉽다",lv:2,tp:"형용사",ex:[{cn:"很容易。",py:"Hěn róngyì.",kr:"매우 쉽다."}]},
{hz:"错",py:"cuò",kr:"틀리다",lv:2,tp:"형용사",ex:[{cn:"你错了。",py:"Nǐ cuò le.",kr:"네가 틀렸다."}]},
{hz:"晴",py:"qíng",kr:"맑다",lv:2,tp:"형용사",ex:[{cn:"今天是晴天。",py:"Jīntiān shì qíngtiān.",kr:"오늘은 맑은 날이다."}]},
{hz:"阴",py:"yīn",kr:"흐리다",lv:2,tp:"형용사",ex:[{cn:"阴天。",py:"Yīn tiān.",kr:"흐린 날."}]},
{hz:"早",py:"zǎo",kr:"이르다, 아침",lv:2,tp:"형용사",ex:[{cn:"早上好。",py:"Zǎoshang hǎo.",kr:"좋은 아침."}]},
{hz:"晚",py:"wǎn",kr:"늦다, 저녁",lv:2,tp:"형용사",ex:[{cn:"太晚了。",py:"Tài wǎn le.",kr:"너무 늦었다."}]},
{hz:"帮助",py:"bāngzhù",kr:"돕다",lv:2,tp:"동사",ex:[{cn:"帮助我。",py:"Bāngzhù wǒ.",kr:"나를 도와줘."}]},
{hz:"准备",py:"zhǔnbèi",kr:"준비하다",lv:2,tp:"동사",ex:[{cn:"准备好了。",py:"Zhǔnbèi hǎo le.",kr:"준비 됐다."}]},
{hz:"开始",py:"kāishǐ",kr:"시작하다",lv:2,tp:"동사",ex:[{cn:"开始了。",py:"Kāishǐ le.",kr:"시작했다."}]},
{hz:"完",py:"wán",kr:"끝나다",lv:2,tp:"동사",ex:[{cn:"做完了。",py:"Zuò wán le.",kr:"다 했다."}]},
{hz:"到",py:"dào",kr:"도착하다",lv:2,tp:"동사",ex:[{cn:"到了。",py:"Dào le.",kr:"도착했다."}]},
{hz:"走",py:"zǒu",kr:"걷다, 가다",lv:2,tp:"동사",ex:[{cn:"走路。",py:"Zǒu lù.",kr:"걸어가다."}]},
{hz:"跑",py:"pǎo",kr:"달리다",lv:2,tp:"동사",ex:[{cn:"跑步。",py:"Pǎo bù.",kr:"달리다."}]},
{hz:"进",py:"jìn",kr:"들어가다",lv:2,tp:"동사",ex:[{cn:"进来。",py:"Jìn lái.",kr:"들어와."}]},
{hz:"出",py:"chū",kr:"나가다",lv:2,tp:"동사",ex:[{cn:"出去。",py:"Chūqù.",kr:"나가다."}]},
{hz:"给",py:"gěi",kr:"주다",lv:2,tp:"동사",ex:[{cn:"给你。",py:"Gěi nǐ.",kr:"너에게 줄게."}]},
{hz:"送",py:"sòng",kr:"보내다, 선물하다",lv:2,tp:"동사",ex:[{cn:"送你。",py:"Sòng nǐ.",kr:"너에게 선물하다."}]},
{hz:"告诉",py:"gàosù",kr:"알려주다",lv:2,tp:"동사",ex:[{cn:"告诉我。",py:"Gàosù wǒ.",kr:"나에게 알려줘."}]},
{hz:"知道",py:"zhīdào",kr:"알다",lv:2,tp:"동사",ex:[{cn:"我知道。",py:"Wǒ zhīdào.",kr:"나는 안다."}]},
{hz:"觉得",py:"juédé",kr:"느끼다, 생각하다",lv:2,tp:"동사",ex:[{cn:"我觉得很好。",py:"Wǒ juédé hěn hǎo.",kr:"좋다고 생각한다."}]},
{hz:"希望",py:"xīwàng",kr:"희망하다",lv:2,tp:"동사",ex:[{cn:"我希望你来。",py:"Wǒ xīwàng nǐ lái.",kr:"네가 오길 바란다."}]},
{hz:"等",py:"děng",kr:"기다리다",lv:2,tp:"동사",ex:[{cn:"等一下。",py:"Děng yīxià.",kr:"잠깐 기다려."}]},
{hz:"找",py:"zhǎo",kr:"찾다",lv:2,tp:"동사",ex:[{cn:"找工作。",py:"Zhǎo gōngzuò.",kr:"일자리를 찾다."}]},
{hz:"穿",py:"chuān",kr:"입다",lv:2,tp:"동사",ex:[{cn:"穿衣服。",py:"Chuān yīfú.",kr:"옷을 입다."}]},
{hz:"玩",py:"wán",kr:"놀다",lv:2,tp:"동사",ex:[{cn:"出去玩。",py:"Chūqù wán.",kr:"나가서 놀다."}]},
{hz:"唱歌",py:"chàng gē",kr:"노래하다",lv:2,tp:"동사",ex:[{cn:"唱歌很好听。",py:"Chàng gē hěn hǎotīng.",kr:"노래를 잘 한다."}]},
{hz:"跳舞",py:"tiào wǔ",kr:"춤추다",lv:2,tp:"동사",ex:[{cn:"她喜欢跳舞。",py:"Tā xǐhuān tiào wǔ.",kr:"그녀는 춤추기를 좋아한다."}]},
{hz:"游泳",py:"yóu yǒng",kr:"수영하다",lv:2,tp:"동사",ex:[{cn:"去游泳。",py:"Qù yóu yǒng.",kr:"수영하러 가다."}]},
{hz:"踢足球",py:"tī zúqiú",kr:"축구하다",lv:2,tp:"동사",ex:[{cn:"踢足球。",py:"Tī zúqiú.",kr:"축구를 하다."}]},
{hz:"打篮球",py:"dǎ lánqiú",kr:"농구하다",lv:2,tp:"동사",ex:[{cn:"打篮球。",py:"Dǎ lánqiú.",kr:"농구를 하다."}]},
{hz:"旅游",py:"lǚyóu",kr:"여행하다",lv:2,tp:"동사",ex:[{cn:"去旅游。",py:"Qù lǚyóu.",kr:"여행가다."}]},
{hz:"介绍",py:"jièshào",kr:"소개하다",lv:2,tp:"동사",ex:[{cn:"自我介绍。",py:"Zìwǒ jièshào.",kr:"자기소개."}]},
{hz:"考试",py:"kǎoshì",kr:"시험",lv:2,tp:"명사/동사",ex:[{cn:"明天考试。",py:"Míngtiān kǎoshì.",kr:"내일 시험이다."}]},
{hz:"笑",py:"xiào",kr:"웃다",lv:2,tp:"동사",ex:[{cn:"他在笑。",py:"Tā zài xiào.",kr:"그가 웃고 있다."}]},
{hz:"哭",py:"kū",kr:"울다",lv:2,tp:"동사",ex:[{cn:"她哭了。",py:"Tā kū le.",kr:"그녀가 울었다."}]},
{hz:"洗",py:"xǐ",kr:"씻다",lv:2,tp:"동사",ex:[{cn:"洗手。",py:"Xǐ shǒu.",kr:"손을 씻다."}]},
{hz:"让",py:"ràng",kr:"~하게 하다",lv:2,tp:"동사",ex:[{cn:"让我想想。",py:"Ràng wǒ xiǎngxiǎng.",kr:"생각 좀 하게 해줘."}]},
{hz:"运动",py:"yùndòng",kr:"운동",lv:2,tp:"명사",ex:[{cn:"做运动。",py:"Zuò yùndòng.",kr:"운동을 하다."}]},
{hz:"身体",py:"shēntǐ",kr:"몸, 신체",lv:2,tp:"명사",ex:[{cn:"身体好。",py:"Shēntǐ hǎo.",kr:"몸이 좋다."}]},
{hz:"眼睛",py:"yǎnjīng",kr:"눈",lv:2,tp:"명사",ex:[{cn:"大眼睛。",py:"Dà yǎnjīng.",kr:"큰 눈."}]},
{hz:"手",py:"shǒu",kr:"손",lv:2,tp:"명사",ex:[{cn:"洗手。",py:"Xǐ shǒu.",kr:"손을 씻다."}]},
{hz:"脸",py:"liǎn",kr:"얼굴",lv:2,tp:"명사",ex:[{cn:"洗脸。",py:"Xǐ liǎn.",kr:"세수하다."}]},
{hz:"头",py:"tóu",kr:"머리",lv:2,tp:"명사",ex:[{cn:"头疼。",py:"Tóu téng.",kr:"머리가 아프다."}]},
{hz:"鸡蛋",py:"jīdàn",kr:"달걀",lv:2,tp:"명사",ex:[{cn:"吃鸡蛋。",py:"Chī jīdàn.",kr:"달걀을 먹다."}]},
{hz:"牛奶",py:"niúnǎi",kr:"우유",lv:2,tp:"명사",ex:[{cn:"喝牛奶。",py:"Hē niúnǎi.",kr:"우유를 마시다."}]},
{hz:"鱼",py:"yú",kr:"물고기",lv:2,tp:"명사",ex:[{cn:"吃鱼。",py:"Chī yú.",kr:"생선을 먹다."}]},
{hz:"羊肉",py:"yángròu",kr:"양고기",lv:2,tp:"명사",ex:[{cn:"吃羊肉。",py:"Chī yángròu.",kr:"양고기를 먹다."}]},
{hz:"西瓜",py:"xīguā",kr:"수박",lv:2,tp:"명사",ex:[{cn:"吃西瓜。",py:"Chī xīguā.",kr:"수박을 먹다."}]},
{hz:"咖啡",py:"kāfēi",kr:"커피",lv:2,tp:"명사",ex:[{cn:"喝咖啡。",py:"Hē kāfēi.",kr:"커피를 마시다."}]},
{hz:"面条",py:"miàntiáo",kr:"면, 국수",lv:2,tp:"명사",ex:[{cn:"吃面条。",py:"Chī miàntiáo.",kr:"국수를 먹다."}]},
{hz:"药",py:"yào",kr:"약",lv:2,tp:"명사",ex:[{cn:"吃药。",py:"Chī yào.",kr:"약을 먹다."}]},
{hz:"手机",py:"shǒujī",kr:"핸드폰",lv:2,tp:"명사",ex:[{cn:"用手机。",py:"Yòng shǒujī.",kr:"핸드폰을 쓰다."}]},
{hz:"手表",py:"shǒubiǎo",kr:"손목시계",lv:2,tp:"명사",ex:[{cn:"看手表。",py:"Kàn shǒubiǎo.",kr:"시계를 보다."}]},
{hz:"自行车",py:"zìxíngchē",kr:"자전거",lv:2,tp:"명사",ex:[{cn:"骑自行车。",py:"Qí zìxíngchē.",kr:"자전거를 타다."}]},
{hz:"公共汽车",py:"gōnggòng qìchē",kr:"버스",lv:2,tp:"명사",ex:[{cn:"坐公共汽车。",py:"Zuò gōnggòng qìchē.",kr:"버스를 타다."}]},
{hz:"火车站",py:"huǒchē zhàn",kr:"기차역",lv:2,tp:"명사",ex:[{cn:"去火车站。",py:"Qù huǒchē zhàn.",kr:"기차역에 가다."}]},
{hz:"机场",py:"jīchǎng",kr:"공항",lv:2,tp:"명사",ex:[{cn:"去机场。",py:"Qù jīchǎng.",kr:"공항에 가다."}]},
{hz:"房间",py:"fángjiān",kr:"방",lv:2,tp:"명사",ex:[{cn:"我的房间。",py:"Wǒ de fángjiān.",kr:"나의 방."}]},
{hz:"教室",py:"jiàoshì",kr:"교실",lv:2,tp:"명사",ex:[{cn:"在教室。",py:"Zài jiàoshì.",kr:"교실에 있다."}]},
{hz:"公司",py:"gōngsī",kr:"회사",lv:2,tp:"명사",ex:[{cn:"去公司。",py:"Qù gōngsī.",kr:"회사에 가다."}]},
{hz:"问题",py:"wèntí",kr:"문제, 질문",lv:2,tp:"명사",ex:[{cn:"有问题。",py:"Yǒu wèntí.",kr:"문제가 있다."}]},
{hz:"时间",py:"shíjiān",kr:"시간",lv:2,tp:"명사",ex:[{cn:"没有时间。",py:"Méiyǒu shíjiān.",kr:"시간이 없다."}]},
{hz:"事情",py:"shìqíng",kr:"일, 사건",lv:2,tp:"명사",ex:[{cn:"什么事情？",py:"Shénme shìqíng?",kr:"무슨 일이야?"}]},
{hz:"颜色",py:"yánsè",kr:"색깔",lv:2,tp:"명사",ex:[{cn:"什么颜色？",py:"Shénme yánsè?",kr:"무슨 색이야?"}]},
{hz:"生日",py:"shēngrì",kr:"생일",lv:2,tp:"명사",ex:[{cn:"生日快乐！",py:"Shēngrì kuàilè!",kr:"생일 축하해!"}]},
{hz:"报纸",py:"bàozhǐ",kr:"신문",lv:2,tp:"명사",ex:[{cn:"看报纸。",py:"Kàn bàozhǐ.",kr:"신문을 보다."}]},
{hz:"门",py:"mén",kr:"문",lv:2,tp:"명사",ex:[{cn:"开门。",py:"Kāi mén.",kr:"문을 열다."}]},
{hz:"路",py:"lù",kr:"길",lv:2,tp:"명사",ex:[{cn:"走路。",py:"Zǒu lù.",kr:"길을 걷다."}]},
{hz:"丈夫",py:"zhàngfū",kr:"남편",lv:2,tp:"명사",ex:[{cn:"我的丈夫。",py:"Wǒ de zhàngfū.",kr:"나의 남편."}]},
{hz:"妻子",py:"qīzi",kr:"아내",lv:2,tp:"명사",ex:[{cn:"他的妻子。",py:"Tā de qīzi.",kr:"그의 아내."}]},
{hz:"哥哥",py:"gēge",kr:"형, 오빠",lv:2,tp:"명사",ex:[{cn:"我哥哥。",py:"Wǒ gēge.",kr:"나의 형/오빠."}]},
{hz:"姐姐",py:"jiějie",kr:"언니, 누나",lv:2,tp:"명사",ex:[{cn:"我姐姐。",py:"Wǒ jiějie.",kr:"나의 언니/누나."}]},
{hz:"弟弟",py:"dìdi",kr:"남동생",lv:2,tp:"명사",ex:[{cn:"我弟弟。",py:"Wǒ dìdi.",kr:"나의 남동생."}]},
{hz:"妹妹",py:"mèimei",kr:"여동생",lv:2,tp:"명사",ex:[{cn:"我妹妹。",py:"Wǒ mèimei.",kr:"나의 여동생."}]},
{hz:"孩子",py:"háizi",kr:"아이",lv:2,tp:"명사",ex:[{cn:"小孩子。",py:"Xiǎo háizi.",kr:"어린아이."}]},
{hz:"男",py:"nán",kr:"남자",lv:2,tp:"명사",ex:[{cn:"男人。",py:"Nán rén.",kr:"남자."}]},
{hz:"女",py:"nǚ",kr:"여자",lv:2,tp:"명사",ex:[{cn:"女人。",py:"Nǚ rén.",kr:"여자."}]},
{hz:"每",py:"měi",kr:"매, 각",lv:2,tp:"대명사",ex:[{cn:"每天。",py:"Měi tiān.",kr:"매일."}]},
{hz:"为什么",py:"wèi shénme",kr:"왜",lv:2,tp:"대명사",ex:[{cn:"为什么？",py:"Wèi shénme?",kr:"왜?"}]},
{hz:"第一",py:"dì yī",kr:"첫 번째",lv:2,tp:"수사",ex:[{cn:"第一次。",py:"Dì yī cì.",kr:"첫 번째."}]},
{hz:"千",py:"qiān",kr:"천",lv:2,tp:"수사",ex:[{cn:"一千块。",py:"Yī qiān kuài.",kr:"1000위안."}]},
{hz:"次",py:"cì",kr:"번, 차례",lv:2,tp:"양사",ex:[{cn:"一次。",py:"Yī cì.",kr:"한 번."}]},
{hz:"从",py:"cóng",kr:"~에서부터",lv:2,tp:"전치사",ex:[{cn:"从这儿走。",py:"Cóng zhèr zǒu.",kr:"여기서부터 가다."}]},
{hz:"向",py:"xiàng",kr:"~쪽으로",lv:2,tp:"전치사",ex:[{cn:"向左走。",py:"Xiàng zuǒ zǒu.",kr:"왼쪽으로 가다."}]},
{hz:"离",py:"lí",kr:"~로부터(거리)",lv:2,tp:"전치사",ex:[{cn:"离这儿很近。",py:"Lí zhèr hěn jìn.",kr:"여기서 가깝다."}]},
{hz:"左",py:"zuǒ",kr:"왼쪽",lv:2,tp:"명사",ex:[{cn:"向左。",py:"Xiàng zuǒ.",kr:"왼쪽으로."}]},
{hz:"右",py:"yòu",kr:"오른쪽",lv:2,tp:"명사",ex:[{cn:"向右。",py:"Xiàng yòu.",kr:"오른쪽으로."}]},
{hz:"旁边",py:"pángbiān",kr:"옆",lv:2,tp:"명사",ex:[{cn:"在旁边。",py:"Zài pángbiān.",kr:"옆에 있다."}]},
{hz:"外",py:"wài",kr:"바깥",lv:2,tp:"명사",ex:[{cn:"外面。",py:"Wàimiàn.",kr:"바깥."}]},
{hz:"晚上",py:"wǎnshang",kr:"저녁, 밤",lv:2,tp:"명사",ex:[{cn:"晚上好。",py:"Wǎnshang hǎo.",kr:"안녕하세요(저녁)."}]},
{hz:"早上",py:"zǎoshang",kr:"아침",lv:2,tp:"명사",ex:[{cn:"早上好。",py:"Zǎoshang hǎo.",kr:"좋은 아침."}]},
{hz:"去年",py:"qùnián",kr:"작년",lv:2,tp:"명사",ex:[{cn:"去年夏天。",py:"Qùnián xiàtiān.",kr:"작년 여름."}]},
{hz:"号",py:"hào",kr:"호, 일(날짜)",lv:2,tp:"명사",ex:[{cn:"三月五号。",py:"Sān yuè wǔ hào.",kr:"3월 5일."}]},
{hz:"生病",py:"shēng bìng",kr:"병에 걸리다",lv:2,tp:"동사",ex:[{cn:"他生病了。",py:"Tā shēng bìng le.",kr:"그가 병에 걸렸다."}]},
{hz:"意思",py:"yìsi",kr:"뜻, 의미",lv:2,tp:"명사",ex:[{cn:"什么意思？",py:"Shénme yìsi?",kr:"무슨 뜻이야?"}]},
{hz:"非常",py:"fēicháng",kr:"매우",lv:2,tp:"부사",ex:[{cn:"非常好。",py:"Fēicháng hǎo.",kr:"매우 좋다."}]},
{hz:"一下",py:"yīxià",kr:"잠깐, 한번",lv:2,tp:"부사",ex:[{cn:"看一下。",py:"Kàn yīxià.",kr:"한번 봐."}]},
{hz:"得",py:"de",kr:"~하게(보어)",lv:2,tp:"조사",ex:[{cn:"说得好。",py:"Shuō de hǎo.",kr:"잘 말한다."}]},
{hz:"过",py:"guò",kr:"~한 적이 있다",lv:2,tp:"조사",ex:[{cn:"我去过。",py:"Wǒ qù guò.",kr:"가본 적이 있다."}]},
{hz:"着",py:"zhe",kr:"~하고 있다(진행)",lv:2,tp:"조사",ex:[{cn:"坐着。",py:"Zuò zhe.",kr:"앉아 있다."}]},
{hz:"把",py:"bǎ",kr:"~을(처치문)",lv:2,tp:"전치사",ex:[{cn:"把门关上。",py:"Bǎ mén guān shàng.",kr:"문을 닫아."}]},
{hz:"被",py:"bèi",kr:"~에게 당하다(피동)",lv:2,tp:"전치사",ex:[{cn:"被他看到了。",py:"Bèi tā kàn dào le.",kr:"그에게 들켰다."}]},

// ===== HSK 3 (300 words) =====
{hz:"关系",py:"guānxì",kr:"관계",lv:3,tp:"명사",ex:[{cn:"没关系。",py:"Méi guānxì.",kr:"괜찮아요."}]},
{hz:"经验",py:"jīngyàn",kr:"경험",lv:3,tp:"명사",ex:[{cn:"有经验。",py:"Yǒu jīngyàn.",kr:"경험이 있다."}]},
{hz:"机会",py:"jīhuì",kr:"기회",lv:3,tp:"명사",ex:[{cn:"好机会。",py:"Hǎo jīhuì.",kr:"좋은 기회."}]},
{hz:"环境",py:"huánjìng",kr:"환경",lv:3,tp:"명사",ex:[{cn:"环境很好。",py:"Huánjìng hěn hǎo.",kr:"환경이 좋다."}]},
{hz:"文化",py:"wénhuà",kr:"문화",lv:3,tp:"명사",ex:[{cn:"中国文化。",py:"Zhōngguó wénhuà.",kr:"중국 문화."}]},
{hz:"历史",py:"lìshǐ",kr:"역사",lv:3,tp:"명사",ex:[{cn:"中国历史。",py:"Zhōngguó lìshǐ.",kr:"중국 역사."}]},
{hz:"经济",py:"jīngjì",kr:"경제",lv:3,tp:"명사",ex:[{cn:"经济发展。",py:"Jīngjì fāzhǎn.",kr:"경제 발전."}]},
{hz:"社会",py:"shèhuì",kr:"사회",lv:3,tp:"명사",ex:[{cn:"社会问题。",py:"Shèhuì wèntí.",kr:"사회 문제."}]},
{hz:"世界",py:"shìjiè",kr:"세계",lv:3,tp:"명사",ex:[{cn:"全世界。",py:"Quán shìjiè.",kr:"전 세계."}]},
{hz:"国家",py:"guójiā",kr:"국가",lv:3,tp:"명사",ex:[{cn:"每个国家。",py:"Měi gè guójiā.",kr:"모든 나라."}]},
{hz:"城市",py:"chéngshì",kr:"도시",lv:3,tp:"명사",ex:[{cn:"大城市。",py:"Dà chéngshì.",kr:"대도시."}]},
{hz:"地方",py:"dìfāng",kr:"장소",lv:3,tp:"명사",ex:[{cn:"什么地方？",py:"Shénme dìfāng?",kr:"어떤 곳?"}]},
{hz:"地图",py:"dìtú",kr:"지도",lv:3,tp:"명사",ex:[{cn:"看地图。",py:"Kàn dìtú.",kr:"지도를 보다."}]},
{hz:"地铁",py:"dìtiě",kr:"지하철",lv:3,tp:"명사",ex:[{cn:"坐地铁。",py:"Zuò dìtiě.",kr:"지하철을 타다."}]},
{hz:"季节",py:"jìjié",kr:"계절",lv:3,tp:"명사",ex:[{cn:"四个季节。",py:"Sì gè jìjié.",kr:"네 계절."}]},
{hz:"春",py:"chūn",kr:"봄",lv:3,tp:"명사",ex:[{cn:"春天来了。",py:"Chūntiān lái le.",kr:"봄이 왔다."}]},
{hz:"夏",py:"xià",kr:"여름",lv:3,tp:"명사",ex:[{cn:"夏天很热。",py:"Xiàtiān hěn rè.",kr:"여름은 덥다."}]},
{hz:"秋",py:"qiū",kr:"가을",lv:3,tp:"명사",ex:[{cn:"秋天来了。",py:"Qiūtiān lái le.",kr:"가을이 왔다."}]},
{hz:"冬",py:"dōng",kr:"겨울",lv:3,tp:"명사",ex:[{cn:"冬天很冷。",py:"Dōngtiān hěn lěng.",kr:"겨울은 춥다."}]},
{hz:"花",py:"huā",kr:"꽃",lv:3,tp:"명사",ex:[{cn:"美丽的花。",py:"Měilì de huā.",kr:"아름다운 꽃."}]},
{hz:"树",py:"shù",kr:"나무",lv:3,tp:"명사",ex:[{cn:"大树。",py:"Dà shù.",kr:"큰 나무."}]},
{hz:"河",py:"hé",kr:"강",lv:3,tp:"명사",ex:[{cn:"大河。",py:"Dà hé.",kr:"큰 강."}]},
{hz:"山",py:"shān",kr:"산",lv:3,tp:"명사",ex:[{cn:"高山。",py:"Gāo shān.",kr:"높은 산."}]},
{hz:"风",py:"fēng",kr:"바람",lv:3,tp:"명사",ex:[{cn:"刮风了。",py:"Guā fēng le.",kr:"바람이 분다."}]},
{hz:"雪",py:"xuě",kr:"눈",lv:3,tp:"명사",ex:[{cn:"下雪了。",py:"Xià xuě le.",kr:"눈이 온다."}]},
{hz:"太阳",py:"tàiyáng",kr:"태양",lv:3,tp:"명사",ex:[{cn:"太阳出来了。",py:"Tàiyáng chūlái le.",kr:"해가 떴다."}]},
{hz:"月亮",py:"yuèliang",kr:"달",lv:3,tp:"명사",ex:[{cn:"月亮很亮。",py:"Yuèliang hěn liàng.",kr:"달이 밝다."}]},
{hz:"动物",py:"dòngwù",kr:"동물",lv:3,tp:"명사",ex:[{cn:"小动物。",py:"Xiǎo dòngwù.",kr:"작은 동물."}]},
{hz:"鸟",py:"niǎo",kr:"새",lv:3,tp:"명사",ex:[{cn:"小鸟。",py:"Xiǎo niǎo.",kr:"작은 새."}]},
{hz:"猫",py:"māo",kr:"고양이",lv:3,tp:"명사",ex:[{cn:"小猫。",py:"Xiǎo māo.",kr:"작은 고양이."}]},
{hz:"狗",py:"gǒu",kr:"개",lv:3,tp:"명사",ex:[{cn:"小狗。",py:"Xiǎo gǒu.",kr:"강아지."}]},
{hz:"马",py:"mǎ",kr:"말",lv:3,tp:"명사",ex:[{cn:"骑马。",py:"Qí mǎ.",kr:"말을 타다."}]},
{hz:"节目",py:"jiémù",kr:"프로그램",lv:3,tp:"명사",ex:[{cn:"电视节目。",py:"Diànshì jiémù.",kr:"TV 프로그램."}]},
{hz:"新闻",py:"xīnwén",kr:"뉴스",lv:3,tp:"명사",ex:[{cn:"看新闻。",py:"Kàn xīnwén.",kr:"뉴스를 보다."}]},
{hz:"照片",py:"zhàopiàn",kr:"사진",lv:3,tp:"명사",ex:[{cn:"拍照片。",py:"Pāi zhàopiàn.",kr:"사진을 찍다."}]},
{hz:"音乐",py:"yīnyuè",kr:"음악",lv:3,tp:"명사",ex:[{cn:"听音乐。",py:"Tīng yīnyuè.",kr:"음악을 듣다."}]},
{hz:"故事",py:"gùshì",kr:"이야기",lv:3,tp:"명사",ex:[{cn:"讲故事。",py:"Jiǎng gùshì.",kr:"이야기를 하다."}]},
{hz:"作业",py:"zuòyè",kr:"숙제",lv:3,tp:"명사",ex:[{cn:"做作业。",py:"Zuò zuòyè.",kr:"숙제를 하다."}]},
{hz:"黑板",py:"hēibǎn",kr:"칠판",lv:3,tp:"명사",ex:[{cn:"看黑板。",py:"Kàn hēibǎn.",kr:"칠판을 보다."}]},
{hz:"词典",py:"cídiǎn",kr:"사전",lv:3,tp:"명사",ex:[{cn:"查词典。",py:"Chá cídiǎn.",kr:"사전을 찾다."}]},
{hz:"练习",py:"liànxí",kr:"연습",lv:3,tp:"명사/동사",ex:[{cn:"做练习。",py:"Zuò liànxí.",kr:"연습하다."}]},
{hz:"数学",py:"shùxué",kr:"수학",lv:3,tp:"명사",ex:[{cn:"学数学。",py:"Xué shùxué.",kr:"수학을 배우다."}]},
{hz:"中文",py:"zhōngwén",kr:"중국어(문어)",lv:3,tp:"명사",ex:[{cn:"学中文。",py:"Xué zhōngwén.",kr:"중국어를 배우다."}]},
{hz:"爷爷",py:"yéye",kr:"할아버지",lv:3,tp:"명사",ex:[{cn:"我爷爷。",py:"Wǒ yéye.",kr:"우리 할아버지."}]},
{hz:"奶奶",py:"nǎinai",kr:"할머니",lv:3,tp:"명사",ex:[{cn:"我奶奶。",py:"Wǒ nǎinai.",kr:"우리 할머니."}]},
{hz:"叔叔",py:"shūshu",kr:"아저씨, 삼촌",lv:3,tp:"명사",ex:[{cn:"王叔叔。",py:"Wáng shūshu.",kr:"왕 아저씨."}]},
{hz:"阿姨",py:"āyí",kr:"아주머니, 이모",lv:3,tp:"명사",ex:[{cn:"李阿姨。",py:"Lǐ āyí.",kr:"이 아주머니."}]},
{hz:"邻居",py:"línjū",kr:"이웃",lv:3,tp:"명사",ex:[{cn:"好邻居。",py:"Hǎo línjū.",kr:"좋은 이웃."}]},
{hz:"客人",py:"kèrén",kr:"손님",lv:3,tp:"명사",ex:[{cn:"有客人。",py:"Yǒu kèrén.",kr:"손님이 있다."}]},
{hz:"经理",py:"jīnglǐ",kr:"매니저, 사장",lv:3,tp:"명사",ex:[{cn:"王经理。",py:"Wáng jīnglǐ.",kr:"왕 사장님."}]},
{hz:"司机",py:"sījī",kr:"운전사",lv:3,tp:"명사",ex:[{cn:"出租车司机。",py:"Chūzūchē sījī.",kr:"택시 기사."}]},
{hz:"银行",py:"yínháng",kr:"은행",lv:3,tp:"명사",ex:[{cn:"去银行。",py:"Qù yínháng.",kr:"은행에 가다."}]},
{hz:"超市",py:"chāoshì",kr:"슈퍼마켓",lv:3,tp:"명사",ex:[{cn:"去超市。",py:"Qù chāoshì.",kr:"슈퍼에 가다."}]},
{hz:"图书馆",py:"túshūguǎn",kr:"도서관",lv:3,tp:"명사",ex:[{cn:"在图书馆。",py:"Zài túshūguǎn.",kr:"도서관에서."}]},
{hz:"办公室",py:"bàngōngshì",kr:"사무실",lv:3,tp:"명사",ex:[{cn:"在办公室。",py:"Zài bàngōngshì.",kr:"사무실에서."}]},
{hz:"厨房",py:"chúfáng",kr:"부엌",lv:3,tp:"명사",ex:[{cn:"在厨房做饭。",py:"Zài chúfáng zuò fàn.",kr:"부엌에서 요리하다."}]},
{hz:"洗手间",py:"xǐshǒujiān",kr:"화장실",lv:3,tp:"명사",ex:[{cn:"洗手间在哪儿？",py:"Xǐshǒujiān zài nǎr?",kr:"화장실이 어디예요?"}]},
{hz:"楼",py:"lóu",kr:"층, 건물",lv:3,tp:"명사",ex:[{cn:"三楼。",py:"Sān lóu.",kr:"3층."}]},
{hz:"电梯",py:"diàntī",kr:"엘리베이터",lv:3,tp:"명사",ex:[{cn:"坐电梯。",py:"Zuò diàntī.",kr:"엘리베이터를 타다."}]},
{hz:"护照",py:"hùzhào",kr:"여권",lv:3,tp:"명사",ex:[{cn:"你的护照。",py:"Nǐ de hùzhào.",kr:"너의 여권."}]},
{hz:"行李箱",py:"xínglǐ xiāng",kr:"캐리어",lv:3,tp:"명사",ex:[{cn:"拿行李箱。",py:"Ná xínglǐ xiāng.",kr:"캐리어를 들다."}]},
{hz:"信用卡",py:"xìnyòngkǎ",kr:"신용카드",lv:3,tp:"명사",ex:[{cn:"用信用卡。",py:"Yòng xìnyòngkǎ.",kr:"신용카드를 쓰다."}]},
{hz:"裙子",py:"qúnzi",kr:"치마",lv:3,tp:"명사",ex:[{cn:"穿裙子。",py:"Chuān qúnzi.",kr:"치마를 입다."}]},
{hz:"裤子",py:"kùzi",kr:"바지",lv:3,tp:"명사",ex:[{cn:"穿裤子。",py:"Chuān kùzi.",kr:"바지를 입다."}]},
{hz:"帽子",py:"màozi",kr:"모자",lv:3,tp:"명사",ex:[{cn:"戴帽子。",py:"Dài màozi.",kr:"모자를 쓰다."}]},
{hz:"鞋",py:"xié",kr:"신발",lv:3,tp:"명사",ex:[{cn:"穿鞋。",py:"Chuān xié.",kr:"신발을 신다."}]},
{hz:"眼镜",py:"yǎnjìng",kr:"안경",lv:3,tp:"명사",ex:[{cn:"戴眼镜。",py:"Dài yǎnjìng.",kr:"안경을 쓰다."}]},
{hz:"伞",py:"sǎn",kr:"우산",lv:3,tp:"명사",ex:[{cn:"拿伞。",py:"Ná sǎn.",kr:"우산을 가져가다."}]},
{hz:"碗",py:"wǎn",kr:"그릇",lv:3,tp:"명사",ex:[{cn:"一碗饭。",py:"Yī wǎn fàn.",kr:"밥 한 그릇."}]},
{hz:"筷子",py:"kuàizi",kr:"젓가락",lv:3,tp:"명사",ex:[{cn:"用筷子。",py:"Yòng kuàizi.",kr:"젓가락을 사용하다."}]},
{hz:"糖",py:"táng",kr:"설탕, 사탕",lv:3,tp:"명사",ex:[{cn:"放糖。",py:"Fàng táng.",kr:"설탕을 넣다."}]},
{hz:"香蕉",py:"xiāngjiāo",kr:"바나나",lv:3,tp:"명사",ex:[{cn:"吃香蕉。",py:"Chī xiāngjiāo.",kr:"바나나를 먹다."}]},
{hz:"葡萄",py:"pútáo",kr:"포도",lv:3,tp:"명사",ex:[{cn:"吃葡萄。",py:"Chī pútáo.",kr:"포도를 먹다."}]},
{hz:"蛋糕",py:"dàngāo",kr:"케이크",lv:3,tp:"명사",ex:[{cn:"生日蛋糕。",py:"Shēngrì dàngāo.",kr:"생일 케이크."}]},
{hz:"啤酒",py:"píjiǔ",kr:"맥주",lv:3,tp:"명사",ex:[{cn:"喝啤酒。",py:"Hē píjiǔ.",kr:"맥주를 마시다."}]},
{hz:"决定",py:"juédìng",kr:"결정하다",lv:3,tp:"동사",ex:[{cn:"我决定了。",py:"Wǒ juédìng le.",kr:"나는 결정했다."}]},
{hz:"影响",py:"yǐngxiǎng",kr:"영향",lv:3,tp:"명사/동사",ex:[{cn:"影响很大。",py:"Yǐngxiǎng hěn dà.",kr:"영향이 크다."}]},
{hz:"解决",py:"jiějué",kr:"해결하다",lv:3,tp:"동사",ex:[{cn:"解决问题。",py:"Jiějué wèntí.",kr:"문제를 해결하다."}]},
{hz:"发现",py:"fāxiàn",kr:"발견하다",lv:3,tp:"동사",ex:[{cn:"我发现了。",py:"Wǒ fāxiàn le.",kr:"나는 발견했다."}]},
{hz:"变化",py:"biànhuà",kr:"변화",lv:3,tp:"명사/동사",ex:[{cn:"变化很大。",py:"Biànhuà hěn dà.",kr:"변화가 크다."}]},
{hz:"提高",py:"tígāo",kr:"향상시키다",lv:3,tp:"동사",ex:[{cn:"提高水平。",py:"Tígāo shuǐpíng.",kr:"수준을 높이다."}]},
{hz:"发展",py:"fāzhǎn",kr:"발전하다",lv:3,tp:"동사",ex:[{cn:"发展很快。",py:"Fāzhǎn hěn kuài.",kr:"발전이 빠르다."}]},
{hz:"选择",py:"xuǎnzé",kr:"선택하다",lv:3,tp:"동사",ex:[{cn:"选择一个。",py:"Xuǎnzé yī gè.",kr:"하나를 선택하다."}]},
{hz:"参加",py:"cānjiā",kr:"참가하다",lv:3,tp:"동사",ex:[{cn:"参加比赛。",py:"Cānjiā bǐsài.",kr:"시합에 참가하다."}]},
{hz:"比较",py:"bǐjiào",kr:"비교하다, 비교적",lv:3,tp:"동사/부사",ex:[{cn:"比较好。",py:"Bǐjiào hǎo.",kr:"비교적 좋다."}]},
{hz:"注意",py:"zhùyì",kr:"주의하다",lv:3,tp:"동사",ex:[{cn:"请注意。",py:"Qǐng zhùyì.",kr:"주의해 주세요."}]},
{hz:"认为",py:"rènwéi",kr:"~라고 생각하다",lv:3,tp:"동사",ex:[{cn:"我认为对。",py:"Wǒ rènwéi duì.",kr:"나는 맞다고 생각한다."}]},
{hz:"了解",py:"liǎojiě",kr:"이해하다, 알다",lv:3,tp:"동사",ex:[{cn:"了解情况。",py:"Liǎojiě qíngkuàng.",kr:"상황을 이해하다."}]},
{hz:"相信",py:"xiāngxìn",kr:"믿다",lv:3,tp:"동사",ex:[{cn:"我相信你。",py:"Wǒ xiāngxìn nǐ.",kr:"너를 믿는다."}]},
{hz:"表示",py:"biǎoshì",kr:"나타내다",lv:3,tp:"동사",ex:[{cn:"表示感谢。",py:"Biǎoshì gǎnxiè.",kr:"감사를 표하다."}]},
{hz:"需要",py:"xūyào",kr:"필요하다",lv:3,tp:"동사",ex:[{cn:"我需要帮助。",py:"Wǒ xūyào bāngzhù.",kr:"나는 도움이 필요하다."}]},
{hz:"应该",py:"yīnggāi",kr:"~해야 한다",lv:3,tp:"동사",ex:[{cn:"你应该去。",py:"Nǐ yīnggāi qù.",kr:"너는 가야 한다."}]},
{hz:"可能",py:"kěnéng",kr:"~할 수 있다, 아마",lv:3,tp:"동사/부사",ex:[{cn:"可能下雨。",py:"Kěnéng xià yǔ.",kr:"비가 올지도 모른다."}]},
{hz:"必须",py:"bìxū",kr:"반드시 ~해야 한다",lv:3,tp:"부사",ex:[{cn:"必须去。",py:"Bìxū qù.",kr:"반드시 가야 한다."}]},
{hz:"特别",py:"tèbié",kr:"특별히",lv:3,tp:"부사/형용사",ex:[{cn:"特别好。",py:"Tèbié hǎo.",kr:"특별히 좋다."}]},
{hz:"其实",py:"qíshí",kr:"사실은",lv:3,tp:"부사",ex:[{cn:"其实不难。",py:"Qíshí bù nán.",kr:"사실 어렵지 않다."}]},
{hz:"终于",py:"zhōngyú",kr:"마침내",lv:3,tp:"부사",ex:[{cn:"终于到了。",py:"Zhōngyú dào le.",kr:"마침내 도착했다."}]},
{hz:"当然",py:"dāngrán",kr:"당연히",lv:3,tp:"부사",ex:[{cn:"当然可以。",py:"Dāngrán kěyǐ.",kr:"당연히 가능하다."}]},
{hz:"只要",py:"zhǐyào",kr:"~하기만 하면",lv:3,tp:"접속사",ex:[{cn:"只要努力。",py:"Zhǐyào nǔlì.",kr:"노력하기만 하면."}]},
{hz:"如果",py:"rúguǒ",kr:"만약 ~라면",lv:3,tp:"접속사",ex:[{cn:"如果下雨。",py:"Rúguǒ xià yǔ.",kr:"만약 비가 온다면."}]},
{hz:"不但",py:"búdàn",kr:"~뿐만 아니라",lv:3,tp:"접속사",ex:[{cn:"不但好看。",py:"Búdàn hǎokàn.",kr:"예쁠 뿐만 아니라."}]},
{hz:"而且",py:"érqiě",kr:"게다가",lv:3,tp:"접속사",ex:[{cn:"而且便宜。",py:"Érqiě piányi.",kr:"게다가 싸다."}]},
{hz:"或者",py:"huòzhě",kr:"혹은",lv:3,tp:"접속사",ex:[{cn:"茶或者咖啡。",py:"Chá huòzhě kāfēi.",kr:"차 혹은 커피."}]},
{hz:"除了",py:"chúle",kr:"~을 제외하고",lv:3,tp:"전치사",ex:[{cn:"除了他。",py:"Chúle tā.",kr:"그를 제외하고."}]},
{hz:"安全",py:"ānquán",kr:"안전하다",lv:3,tp:"형용사",ex:[{cn:"很安全。",py:"Hěn ānquán.",kr:"매우 안전하다."}]},
{hz:"简单",py:"jiǎndān",kr:"간단하다",lv:3,tp:"형용사",ex:[{cn:"很简单。",py:"Hěn jiǎndān.",kr:"매우 간단하다."}]},
{hz:"复杂",py:"fùzá",kr:"복잡하다",lv:3,tp:"형용사",ex:[{cn:"太复杂了。",py:"Tài fùzá le.",kr:"너무 복잡하다."}]},
{hz:"方便",py:"fāngbiàn",kr:"편리하다",lv:3,tp:"형용사",ex:[{cn:"很方便。",py:"Hěn fāngbiàn.",kr:"매우 편리하다."}]},
{hz:"重要",py:"zhòngyào",kr:"중요하다",lv:3,tp:"형용사",ex:[{cn:"很重要。",py:"Hěn zhòngyào.",kr:"매우 중요하다."}]},
{hz:"清楚",py:"qīngchǔ",kr:"분명하다",lv:3,tp:"형용사",ex:[{cn:"说清楚。",py:"Shuō qīngchǔ.",kr:"분명하게 말하다."}]},
{hz:"丰富",py:"fēngfù",kr:"풍부하다",lv:3,tp:"형용사",ex:[{cn:"经验丰富。",py:"Jīngyàn fēngfù.",kr:"경험이 풍부하다."}]},
{hz:"普通",py:"pǔtōng",kr:"보통의",lv:3,tp:"형용사",ex:[{cn:"普通话。",py:"Pǔtōnghuà.",kr:"표준어."}]},
{hz:"成功",py:"chénggōng",kr:"성공하다",lv:3,tp:"동사/명사",ex:[{cn:"成功了！",py:"Chénggōng le!",kr:"성공했다!"}]},
{hz:"失败",py:"shībài",kr:"실패하다",lv:3,tp:"동사/명사",ex:[{cn:"失败了。",py:"Shībài le.",kr:"실패했다."}]},
{hz:"干净",py:"gānjìng",kr:"깨끗하다",lv:3,tp:"형용사",ex:[{cn:"很干净。",py:"Hěn gānjìng.",kr:"매우 깨끗하다."}]},
{hz:"脏",py:"zāng",kr:"더럽다",lv:3,tp:"형용사",ex:[{cn:"太脏了。",py:"Tài zāng le.",kr:"너무 더럽다."}]},
{hz:"胖",py:"pàng",kr:"뚱뚱하다",lv:3,tp:"형용사",ex:[{cn:"有点胖。",py:"Yǒudiǎn pàng.",kr:"좀 뚱뚱하다."}]},
{hz:"瘦",py:"shòu",kr:"마르다",lv:3,tp:"형용사",ex:[{cn:"太瘦了。",py:"Tài shòu le.",kr:"너무 말랐다."}]},
{hz:"矮",py:"ǎi",kr:"키가 작다",lv:3,tp:"형용사",ex:[{cn:"他很矮。",py:"Tā hěn ǎi.",kr:"그는 키가 작다."}]},
{hz:"聪明",py:"cōngmíng",kr:"똑똑하다",lv:3,tp:"형용사",ex:[{cn:"你很聪明。",py:"Nǐ hěn cōngmíng.",kr:"너는 똑똑하다."}]},
{hz:"可爱",py:"kě'ài",kr:"귀엽다",lv:3,tp:"형용사",ex:[{cn:"很可爱。",py:"Hěn kě'ài.",kr:"매우 귀엽다."}]},
{hz:"奇怪",py:"qíguài",kr:"이상하다",lv:3,tp:"형용사",ex:[{cn:"很奇怪。",py:"Hěn qíguài.",kr:"매우 이상하다."}]},
{hz:"认真",py:"rènzhēn",kr:"진지하다, 성실하다",lv:3,tp:"형용사",ex:[{cn:"认真学习。",py:"Rènzhēn xuéxí.",kr:"열심히 공부하다."}]},
{hz:"满意",py:"mǎnyì",kr:"만족하다",lv:3,tp:"형용사",ex:[{cn:"很满意。",py:"Hěn mǎnyì.",kr:"매우 만족하다."}]},
{hz:"着急",py:"zháojí",kr:"초조하다",lv:3,tp:"형용사",ex:[{cn:"别着急。",py:"Bié zháojí.",kr:"초조해하지 마."}]},
{hz:"害怕",py:"hàipà",kr:"두려워하다",lv:3,tp:"동사",ex:[{cn:"不害怕。",py:"Bú hàipà.",kr:"두렵지 않다."}]},
{hz:"生气",py:"shēng qì",kr:"화나다",lv:3,tp:"동사",ex:[{cn:"别生气。",py:"Bié shēng qì.",kr:"화내지 마."}]},
{hz:"担心",py:"dānxīn",kr:"걱정하다",lv:3,tp:"동사",ex:[{cn:"别担心。",py:"Bié dānxīn.",kr:"걱정하지 마."}]},
{hz:"感兴趣",py:"gǎn xìngqù",kr:"흥미가 있다",lv:3,tp:"동사",ex:[{cn:"我很感兴趣。",py:"Wǒ hěn gǎn xìngqù.",kr:"매우 흥미가 있다."}]},
{hz:"关心",py:"guānxīn",kr:"관심을 갖다",lv:3,tp:"동사",ex:[{cn:"关心你。",py:"Guānxīn nǐ.",kr:"너에게 관심을 갖다."}]},
{hz:"放",py:"fàng",kr:"놓다, 넣다",lv:3,tp:"동사",ex:[{cn:"放在这里。",py:"Fàng zài zhèlǐ.",kr:"여기에 놓다."}]},
{hz:"拿",py:"ná",kr:"들다, 가져가다",lv:3,tp:"동사",ex:[{cn:"拿走。",py:"Ná zǒu.",kr:"가져가다."}]},
{hz:"接",py:"jiē",kr:"받다, 맞이하다",lv:3,tp:"동사",ex:[{cn:"接电话。",py:"Jiē diànhuà.",kr:"전화를 받다."}]},
{hz:"换",py:"huàn",kr:"바꾸다",lv:3,tp:"동사",ex:[{cn:"换衣服。",py:"Huàn yīfú.",kr:"옷을 갈아입다."}]},
{hz:"借",py:"jiè",kr:"빌리다",lv:3,tp:"동사",ex:[{cn:"借书。",py:"Jiè shū.",kr:"책을 빌리다."}]},
{hz:"关",py:"guān",kr:"닫다, 끄다",lv:3,tp:"동사",ex:[{cn:"关门。",py:"Guān mén.",kr:"문을 닫다."}]},
{hz:"打扫",py:"dǎsǎo",kr:"청소하다",lv:3,tp:"동사",ex:[{cn:"打扫房间。",py:"Dǎsǎo fángjiān.",kr:"방을 청소하다."}]},
{hz:"搬",py:"bān",kr:"옮기다",lv:3,tp:"동사",ex:[{cn:"搬家。",py:"Bān jiā.",kr:"이사하다."}]},
{hz:"检查",py:"jiǎnchá",kr:"검사하다",lv:3,tp:"동사",ex:[{cn:"检查身体。",py:"Jiǎnchá shēntǐ.",kr:"건강검진하다."}]},
{hz:"使用",py:"shǐyòng",kr:"사용하다",lv:3,tp:"동사",ex:[{cn:"使用手机。",py:"Shǐyòng shǒujī.",kr:"핸드폰을 사용하다."}]},
{hz:"照顾",py:"zhàogù",kr:"돌보다",lv:3,tp:"동사",ex:[{cn:"照顾孩子。",py:"Zhàogù háizi.",kr:"아이를 돌보다."}]},
{hz:"经过",py:"jīngguò",kr:"지나가다",lv:3,tp:"동사",ex:[{cn:"经过公园。",py:"Jīngguò gōngyuán.",kr:"공원을 지나가다."}]},
{hz:"记得",py:"jìdé",kr:"기억하다",lv:3,tp:"동사",ex:[{cn:"我记得。",py:"Wǒ jìdé.",kr:"나는 기억한다."}]},
{hz:"忘记",py:"wàngjì",kr:"잊다",lv:3,tp:"동사",ex:[{cn:"忘记了。",py:"Wàngjì le.",kr:"잊었다."}]},
{hz:"同意",py:"tóngyì",kr:"동의하다",lv:3,tp:"동사",ex:[{cn:"我同意。",py:"Wǒ tóngyì.",kr:"나는 동의한다."}]},
{hz:"办法",py:"bànfǎ",kr:"방법",lv:3,tp:"명사",ex:[{cn:"好办法。",py:"Hǎo bànfǎ.",kr:"좋은 방법."}]},
{hz:"习惯",py:"xíguàn",kr:"습관, 익숙하다",lv:3,tp:"명사/동사",ex:[{cn:"好习惯。",py:"Hǎo xíguàn.",kr:"좋은 습관."}]},
{hz:"礼物",py:"lǐwù",kr:"선물",lv:3,tp:"명사",ex:[{cn:"送礼物。",py:"Sòng lǐwù.",kr:"선물을 주다."}]},
{hz:"兴趣",py:"xìngqù",kr:"흥미",lv:3,tp:"명사",ex:[{cn:"有兴趣。",py:"Yǒu xìngqù.",kr:"흥미가 있다."}]},
{hz:"爱好",py:"àihào",kr:"취미",lv:3,tp:"명사",ex:[{cn:"你的爱好。",py:"Nǐ de àihào.",kr:"너의 취미."}]},
{hz:"健康",py:"jiànkāng",kr:"건강",lv:3,tp:"명사/형용사",ex:[{cn:"身体健康。",py:"Shēntǐ jiànkāng.",kr:"몸이 건강하다."}]},
{hz:"感冒",py:"gǎnmào",kr:"감기",lv:3,tp:"명사/동사",ex:[{cn:"我感冒了。",py:"Wǒ gǎnmào le.",kr:"나는 감기에 걸렸다."}]},
{hz:"数量",py:"shùliàng",kr:"수량",lv:3,tp:"명사",ex:[{cn:"数量很多。",py:"Shùliàng hěn duō.",kr:"수량이 많다."}]},
{hz:"价格",py:"jiàgé",kr:"가격",lv:3,tp:"명사",ex:[{cn:"价格很高。",py:"Jiàgé hěn gāo.",kr:"가격이 높다."}]},
{hz:"万",py:"wàn",kr:"만",lv:3,tp:"수사",ex:[{cn:"一万块。",py:"Yī wàn kuài.",kr:"만 위안."}]},
{hz:"其他",py:"qítā",kr:"기타, 다른",lv:3,tp:"대명사",ex:[{cn:"其他人。",py:"Qítā rén.",kr:"다른 사람."}]},
{hz:"然后",py:"ránhòu",kr:"그 다음에",lv:3,tp:"접속사",ex:[{cn:"然后去。",py:"Ránhòu qù.",kr:"그 다음에 가다."}]},
{hz:"根据",py:"gēnjù",kr:"~에 근거하여",lv:3,tp:"전치사",ex:[{cn:"根据情况。",py:"Gēnjù qíngkuàng.",kr:"상황에 근거하여."}]},
{hz:"总是",py:"zǒngshì",kr:"항상",lv:3,tp:"부사",ex:[{cn:"他总是迟到。",py:"Tā zǒngshì chídào.",kr:"그는 항상 늦는다."}]},
{hz:"几乎",py:"jīhū",kr:"거의",lv:3,tp:"부사",ex:[{cn:"几乎每天。",py:"Jīhū měi tiān.",kr:"거의 매일."}]},
{hz:"刚才",py:"gāngcái",kr:"방금",lv:3,tp:"부사",ex:[{cn:"刚才说的。",py:"Gāngcái shuō de.",kr:"방금 말한 것."}]},
{hz:"马上",py:"mǎshàng",kr:"곧, 즉시",lv:3,tp:"부사",ex:[{cn:"马上来。",py:"Mǎshàng lái.",kr:"곧 갈게."}]},
{hz:"一直",py:"yīzhí",kr:"계속",lv:3,tp:"부사",ex:[{cn:"一直走。",py:"Yīzhí zǒu.",kr:"계속 걸어가다."}]},
{hz:"只",py:"zhǐ",kr:"단지, 오직",lv:3,tp:"부사",ex:[{cn:"只有一个。",py:"Zhǐ yǒu yī gè.",kr:"단 하나만 있다."}]},
{hz:"更",py:"gèng",kr:"더욱",lv:3,tp:"부사",ex:[{cn:"更好。",py:"Gèng hǎo.",kr:"더 좋다."}]},
{hz:"越",py:"yuè",kr:"점점",lv:3,tp:"부사",ex:[{cn:"越来越好。",py:"Yuè lái yuè hǎo.",kr:"점점 좋아지다."}]},
{hz:"对",py:"duì",kr:"~에 대하여",lv:3,tp:"전치사",ex:[{cn:"对你好。",py:"Duì nǐ hǎo.",kr:"너에게 잘 하다."}]},
{hz:"比",py:"bǐ",kr:"~보다",lv:3,tp:"전치사",ex:[{cn:"比他高。",py:"Bǐ tā gāo.",kr:"그보다 크다."}]},
{hz:"像",py:"xiàng",kr:"~처럼",lv:3,tp:"동사",ex:[{cn:"像他一样。",py:"Xiàng tā yīyàng.",kr:"그처럼."}]},
{hz:"把",py:"bǎ",kr:"~을(처치문)",lv:3,tp:"전치사",ex:[{cn:"把书给我。",py:"Bǎ shū gěi wǒ.",kr:"책을 나에게 줘."}]},
{hz:"段",py:"duàn",kr:"구간, 단락",lv:3,tp:"양사",ex:[{cn:"一段路。",py:"Yī duàn lù.",kr:"한 구간의 길."}]},
{hz:"双",py:"shuāng",kr:"쌍, 켤레",lv:3,tp:"양사",ex:[{cn:"一双鞋。",py:"Yī shuāng xié.",kr:"신발 한 켤레."}]},
{hz:"件",py:"jiàn",kr:"건, 벌(양사)",lv:3,tp:"양사",ex:[{cn:"一件事。",py:"Yī jiàn shì.",kr:"한 가지 일."}]},
{hz:"条",py:"tiáo",kr:"줄, 가닥(양사)",lv:3,tp:"양사",ex:[{cn:"一条路。",py:"Yī tiáo lù.",kr:"한 줄기 길."}]},
{hz:"位",py:"wèi",kr:"분(존칭 양사)",lv:3,tp:"양사",ex:[{cn:"一位老师。",py:"Yī wèi lǎoshī.",kr:"선생님 한 분."}]},

// ===== HSK 4 (600 words - representative selection) =====
{hz:"无论",py:"wúlùn",kr:"~에 상관없이",lv:4,tp:"접속사",ex:[{cn:"无论如何。",py:"Wúlùn rúhé.",kr:"어떻게든."}]},
{hz:"即使",py:"jíshǐ",kr:"설령 ~이라도",lv:4,tp:"접속사",ex:[{cn:"即使下雨。",py:"Jíshǐ xià yǔ.",kr:"설령 비가 와도."}]},
{hz:"况且",py:"kuàngqiě",kr:"게다가, 하물며",lv:4,tp:"접속사",ex:[{cn:"况且他不在。",py:"Kuàngqiě tā bú zài.",kr:"게다가 그가 없다."}]},
{hz:"尽管",py:"jǐnguǎn",kr:"비록 ~이지만",lv:4,tp:"접속사",ex:[{cn:"尽管很难。",py:"Jǐnguǎn hěn nán.",kr:"비록 어렵지만."}]},
{hz:"否则",py:"fǒuzé",kr:"그렇지 않으면",lv:4,tp:"접속사",ex:[{cn:"快走，否则迟到。",py:"Kuài zǒu, fǒuzé chídào.",kr:"빨리 가, 아니면 늦는다."}]},
{hz:"既然",py:"jìrán",kr:"이미 ~한 이상",lv:4,tp:"접속사",ex:[{cn:"既然来了。",py:"Jìrán lái le.",kr:"이미 온 이상."}]},
{hz:"不过",py:"búguò",kr:"그렇지만",lv:4,tp:"접속사",ex:[{cn:"不过没关系。",py:"Búguò méi guānxì.",kr:"그렇지만 괜찮다."}]},
{hz:"于是",py:"yúshì",kr:"그래서",lv:4,tp:"접속사",ex:[{cn:"于是他走了。",py:"Yúshì tā zǒu le.",kr:"그래서 그가 갔다."}]},
{hz:"反映",py:"fǎnyìng",kr:"반영하다",lv:4,tp:"동사",ex:[{cn:"反映问题。",py:"Fǎnyìng wèntí.",kr:"문제를 반영하다."}]},
{hz:"分析",py:"fēnxī",kr:"분석하다",lv:4,tp:"동사",ex:[{cn:"分析原因。",py:"Fēnxī yuányīn.",kr:"원인을 분석하다."}]},
{hz:"讨论",py:"tǎolùn",kr:"토론하다",lv:4,tp:"동사",ex:[{cn:"讨论问题。",py:"Tǎolùn wèntí.",kr:"문제를 토론하다."}]},
{hz:"联系",py:"liánxì",kr:"연락하다",lv:4,tp:"동사",ex:[{cn:"联系我。",py:"Liánxì wǒ.",kr:"나에게 연락해."}]},
{hz:"交流",py:"jiāoliú",kr:"교류하다",lv:4,tp:"동사",ex:[{cn:"文化交流。",py:"Wénhuà jiāoliú.",kr:"문화 교류."}]},
{hz:"保护",py:"bǎohù",kr:"보호하다",lv:4,tp:"동사",ex:[{cn:"保护环境。",py:"Bǎohù huánjìng.",kr:"환경을 보호하다."}]},
{hz:"支持",py:"zhīchí",kr:"지지하다",lv:4,tp:"동사",ex:[{cn:"支持你。",py:"Zhīchí nǐ.",kr:"너를 지지한다."}]},
{hz:"建设",py:"jiànshè",kr:"건설하다",lv:4,tp:"동사",ex:[{cn:"建设国家。",py:"Jiànshè guójiā.",kr:"나라를 건설하다."}]},
{hz:"存在",py:"cúnzài",kr:"존재하다",lv:4,tp:"동사",ex:[{cn:"问题存在。",py:"Wèntí cúnzài.",kr:"문제가 존재한다."}]},
{hz:"实现",py:"shíxiàn",kr:"실현하다",lv:4,tp:"동사",ex:[{cn:"实现梦想。",py:"Shíxiàn mèngxiǎng.",kr:"꿈을 실현하다."}]},
{hz:"获得",py:"huòdé",kr:"획득하다",lv:4,tp:"동사",ex:[{cn:"获得成功。",py:"Huòdé chénggōng.",kr:"성공을 얻다."}]},
{hz:"产生",py:"chǎnshēng",kr:"생기다, 발생하다",lv:4,tp:"동사",ex:[{cn:"产生问题。",py:"Chǎnshēng wèntí.",kr:"문제가 발생하다."}]},
{hz:"表达",py:"biǎodá",kr:"표현하다",lv:4,tp:"동사",ex:[{cn:"表达想法。",py:"Biǎodá xiǎngfǎ.",kr:"생각을 표현하다."}]},
{hz:"承认",py:"chéngrèn",kr:"인정하다",lv:4,tp:"동사",ex:[{cn:"承认错误。",py:"Chéngrèn cuòwù.",kr:"실수를 인정하다."}]},
{hz:"估计",py:"gūjì",kr:"추정하다",lv:4,tp:"동사",ex:[{cn:"我估计他来。",py:"Wǒ gūjì tā lái.",kr:"그가 올 것 같다."}]},
{hz:"安排",py:"ānpái",kr:"배치하다",lv:4,tp:"동사",ex:[{cn:"安排时间。",py:"Ānpái shíjiān.",kr:"시간을 배치하다."}]},
{hz:"降低",py:"jiàngdī",kr:"낮추다",lv:4,tp:"동사",ex:[{cn:"降低价格。",py:"Jiàngdī jiàgé.",kr:"가격을 낮추다."}]},
{hz:"提供",py:"tígōng",kr:"제공하다",lv:4,tp:"동사",ex:[{cn:"提供服务。",py:"Tígōng fúwù.",kr:"서비스를 제공하다."}]},
{hz:"代替",py:"dàitì",kr:"대체하다",lv:4,tp:"동사",ex:[{cn:"代替他。",py:"Dàitì tā.",kr:"그를 대체하다."}]},
{hz:"鼓励",py:"gǔlì",kr:"격려하다",lv:4,tp:"동사",ex:[{cn:"鼓励他。",py:"Gǔlì tā.",kr:"그를 격려하다."}]},
{hz:"吸引",py:"xīyǐn",kr:"끌어들이다",lv:4,tp:"동사",ex:[{cn:"吸引注意。",py:"Xīyǐn zhùyì.",kr:"주의를 끌다."}]},
{hz:"组织",py:"zǔzhī",kr:"조직하다",lv:4,tp:"동사/명사",ex:[{cn:"组织活动。",py:"Zǔzhī huódòng.",kr:"활동을 조직하다."}]},
{hz:"管理",py:"guǎnlǐ",kr:"관리하다",lv:4,tp:"동사",ex:[{cn:"管理公司。",py:"Guǎnlǐ gōngsī.",kr:"회사를 관리하다."}]},
{hz:"适合",py:"shìhé",kr:"적합하다",lv:4,tp:"동사",ex:[{cn:"很适合你。",py:"Hěn shìhé nǐ.",kr:"너에게 적합하다."}]},
{hz:"申请",py:"shēnqǐng",kr:"신청하다",lv:4,tp:"동사",ex:[{cn:"申请工作。",py:"Shēnqǐng gōngzuò.",kr:"일을 신청하다."}]},
{hz:"证明",py:"zhèngmíng",kr:"증명하다",lv:4,tp:"동사",ex:[{cn:"证明自己。",py:"Zhèngmíng zìjǐ.",kr:"자신을 증명하다."}]},
{hz:"培养",py:"péiyǎng",kr:"양성하다, 기르다",lv:4,tp:"동사",ex:[{cn:"培养能力。",py:"Péiyǎng nénglì.",kr:"능력을 기르다."}]},
{hz:"赞成",py:"zànchéng",kr:"찬성하다",lv:4,tp:"동사",ex:[{cn:"我赞成。",py:"Wǒ zànchéng.",kr:"나는 찬성한다."}]},
{hz:"反对",py:"fǎnduì",kr:"반대하다",lv:4,tp:"동사",ex:[{cn:"我反对。",py:"Wǒ fǎnduì.",kr:"나는 반대한다."}]},
{hz:"批评",py:"pīpíng",kr:"비평하다",lv:4,tp:"동사",ex:[{cn:"批评他。",py:"Pīpíng tā.",kr:"그를 비판하다."}]},
{hz:"表演",py:"biǎoyǎn",kr:"공연하다",lv:4,tp:"동사",ex:[{cn:"表演节目。",py:"Biǎoyǎn jiémù.",kr:"프로그램을 공연하다."}]},
{hz:"拒绝",py:"jùjué",kr:"거절하다",lv:4,tp:"동사",ex:[{cn:"拒绝他。",py:"Jùjué tā.",kr:"그를 거절하다."}]},
{hz:"道歉",py:"dàoqiàn",kr:"사과하다",lv:4,tp:"동사",ex:[{cn:"向你道歉。",py:"Xiàng nǐ dàoqiàn.",kr:"너에게 사과하다."}]},
{hz:"修理",py:"xiūlǐ",kr:"수리하다",lv:4,tp:"동사",ex:[{cn:"修理电脑。",py:"Xiūlǐ diànnǎo.",kr:"컴퓨터를 수리하다."}]},
{hz:"积极",py:"jījí",kr:"적극적이다",lv:4,tp:"형용사",ex:[{cn:"态度积极。",py:"Tàidù jījí.",kr:"태도가 적극적이다."}]},
{hz:"严格",py:"yángé",kr:"엄격하다",lv:4,tp:"형용사",ex:[{cn:"要求严格。",py:"Yāoqiú yángé.",kr:"요구가 엄격하다."}]},
{hz:"合理",py:"hélǐ",kr:"합리적이다",lv:4,tp:"형용사",ex:[{cn:"很合理。",py:"Hěn hélǐ.",kr:"매우 합리적이다."}]},
{hz:"明显",py:"míngxiǎn",kr:"분명하다",lv:4,tp:"형용사",ex:[{cn:"效果明显。",py:"Xiàoguǒ míngxiǎn.",kr:"효과가 분명하다."}]},
{hz:"具体",py:"jùtǐ",kr:"구체적이다",lv:4,tp:"형용사",ex:[{cn:"具体计划。",py:"Jùtǐ jìhuà.",kr:"구체적 계획."}]},
{hz:"实际",py:"shíjì",kr:"실제적이다",lv:4,tp:"형용사",ex:[{cn:"实际情况。",py:"Shíjì qíngkuàng.",kr:"실제 상황."}]},
{hz:"基本",py:"jīběn",kr:"기본적이다",lv:4,tp:"형용사",ex:[{cn:"基本条件。",py:"Jīběn tiáojiàn.",kr:"기본 조건."}]},
{hz:"正常",py:"zhèngcháng",kr:"정상적이다",lv:4,tp:"형용사",ex:[{cn:"很正常。",py:"Hěn zhèngcháng.",kr:"매우 정상적이다."}]},
{hz:"正式",py:"zhèngshì",kr:"정식이다",lv:4,tp:"형용사",ex:[{cn:"正式开始。",py:"Zhèngshì kāishǐ.",kr:"정식으로 시작."}]},
{hz:"及时",py:"jíshí",kr:"적시에",lv:4,tp:"형용사",ex:[{cn:"及时到。",py:"Jíshí dào.",kr:"제때 도착하다."}]},
{hz:"紧张",py:"jǐnzhāng",kr:"긴장하다",lv:4,tp:"형용사",ex:[{cn:"别紧张。",py:"Bié jǐnzhāng.",kr:"긴장하지 마."}]},
{hz:"温柔",py:"wēnróu",kr:"부드럽다, 상냥하다",lv:4,tp:"형용사",ex:[{cn:"她很温柔。",py:"Tā hěn wēnróu.",kr:"그녀는 상냥하다."}]},
{hz:"幽默",py:"yōumò",kr:"유머러스하다",lv:4,tp:"형용사",ex:[{cn:"他很幽默。",py:"Tā hěn yōumò.",kr:"그는 유머러스하다."}]},
{hz:"诚实",py:"chéngshí",kr:"정직하다",lv:4,tp:"형용사",ex:[{cn:"很诚实。",py:"Hěn chéngshí.",kr:"매우 정직하다."}]},
{hz:"勇敢",py:"yǒnggǎn",kr:"용감하다",lv:4,tp:"형용사",ex:[{cn:"很勇敢。",py:"Hěn yǒnggǎn.",kr:"매우 용감하다."}]},
{hz:"耐心",py:"nàixīn",kr:"인내심이 있다",lv:4,tp:"형용사/명사",ex:[{cn:"有耐心。",py:"Yǒu nàixīn.",kr:"인내심이 있다."}]},
{hz:"效果",py:"xiàoguǒ",kr:"효과",lv:4,tp:"명사",ex:[{cn:"效果很好。",py:"Xiàoguǒ hěn hǎo.",kr:"효과가 좋다."}]},
{hz:"原因",py:"yuányīn",kr:"원인",lv:4,tp:"명사",ex:[{cn:"什么原因？",py:"Shénme yuányīn?",kr:"무슨 원인이야?"}]},
{hz:"结果",py:"jiéguǒ",kr:"결과",lv:4,tp:"명사",ex:[{cn:"结果很好。",py:"Jiéguǒ hěn hǎo.",kr:"결과가 좋다."}]},
{hz:"条件",py:"tiáojiàn",kr:"조건",lv:4,tp:"명사",ex:[{cn:"条件不好。",py:"Tiáojiàn bù hǎo.",kr:"조건이 좋지 않다."}]},
{hz:"情况",py:"qíngkuàng",kr:"상황",lv:4,tp:"명사",ex:[{cn:"情况怎么样？",py:"Qíngkuàng zěnmeyàng?",kr:"상황이 어때?"}]},
{hz:"目的",py:"mùdì",kr:"목적",lv:4,tp:"명사",ex:[{cn:"学习的目的。",py:"Xuéxí de mùdì.",kr:"학습의 목적."}]},
{hz:"态度",py:"tàidù",kr:"태도",lv:4,tp:"명사",ex:[{cn:"态度很好。",py:"Tàidù hěn hǎo.",kr:"태도가 좋다."}]},
{hz:"标准",py:"biāozhǔn",kr:"기준, 표준",lv:4,tp:"명사",ex:[{cn:"标准很高。",py:"Biāozhǔn hěn gāo.",kr:"기준이 높다."}]},
{hz:"方法",py:"fāngfǎ",kr:"방법",lv:4,tp:"명사",ex:[{cn:"好方法。",py:"Hǎo fāngfǎ.",kr:"좋은 방법."}]},
{hz:"方面",py:"fāngmiàn",kr:"방면",lv:4,tp:"명사",ex:[{cn:"各方面。",py:"Gè fāngmiàn.",kr:"각 방면."}]},
{hz:"内容",py:"nèiróng",kr:"내용",lv:4,tp:"명사",ex:[{cn:"内容丰富。",py:"Nèiróng fēngfù.",kr:"내용이 풍부하다."}]},
{hz:"对象",py:"duìxiàng",kr:"대상",lv:4,tp:"명사",ex:[{cn:"研究对象。",py:"Yánjiū duìxiàng.",kr:"연구 대상."}]},
{hz:"过程",py:"guòchéng",kr:"과정",lv:4,tp:"명사",ex:[{cn:"学习过程。",py:"Xuéxí guòchéng.",kr:"학습 과정."}]},
{hz:"计划",py:"jìhuà",kr:"계획",lv:4,tp:"명사/동사",ex:[{cn:"计划好了。",py:"Jìhuà hǎo le.",kr:"계획을 세웠다."}]},
{hz:"水平",py:"shuǐpíng",kr:"수준",lv:4,tp:"명사",ex:[{cn:"水平很高。",py:"Shuǐpíng hěn gāo.",kr:"수준이 높다."}]},
{hz:"能力",py:"nénglì",kr:"능력",lv:4,tp:"명사",ex:[{cn:"有能力。",py:"Yǒu nénglì.",kr:"능력이 있다."}]},
{hz:"力量",py:"lìliàng",kr:"힘",lv:4,tp:"명사",ex:[{cn:"力量很大。",py:"Lìliàng hěn dà.",kr:"힘이 세다."}]},
{hz:"任务",py:"rènwù",kr:"임무",lv:4,tp:"명사",ex:[{cn:"完成任务。",py:"Wánchéng rènwù.",kr:"임무를 완수하다."}]},
{hz:"活动",py:"huódòng",kr:"활동",lv:4,tp:"명사",ex:[{cn:"参加活动。",py:"Cānjiā huódòng.",kr:"활동에 참가하다."}]},
{hz:"比赛",py:"bǐsài",kr:"시합",lv:4,tp:"명사",ex:[{cn:"参加比赛。",py:"Cānjiā bǐsài.",kr:"시합에 참가하다."}]},
{hz:"知识",py:"zhīshì",kr:"지식",lv:4,tp:"명사",ex:[{cn:"学习知识。",py:"Xuéxí zhīshì.",kr:"지식을 배우다."}]},
{hz:"教育",py:"jiàoyù",kr:"교육",lv:4,tp:"명사",ex:[{cn:"教育很重要。",py:"Jiàoyù hěn zhòngyào.",kr:"교육이 중요하다."}]},
{hz:"科学",py:"kēxué",kr:"과학",lv:4,tp:"명사",ex:[{cn:"科学技术。",py:"Kēxué jìshù.",kr:"과학 기술."}]},
{hz:"艺术",py:"yìshù",kr:"예술",lv:4,tp:"명사",ex:[{cn:"艺术作品。",py:"Yìshù zuòpǐn.",kr:"예술 작품."}]},
{hz:"风格",py:"fēnggé",kr:"스타일",lv:4,tp:"명사",ex:[{cn:"不同风格。",py:"Bùtóng fēnggé.",kr:"다른 스타일."}]},
{hz:"印象",py:"yìnxiàng",kr:"인상",lv:4,tp:"명사",ex:[{cn:"第一印象。",py:"Dì yī yìnxiàng.",kr:"첫인상."}]},
{hz:"梦想",py:"mèngxiǎng",kr:"꿈",lv:4,tp:"명사",ex:[{cn:"我的梦想。",py:"Wǒ de mèngxiǎng.",kr:"나의 꿈."}]},
{hz:"责任",py:"zérèn",kr:"책임",lv:4,tp:"명사",ex:[{cn:"有责任。",py:"Yǒu zérèn.",kr:"책임이 있다."}]},
{hz:"信息",py:"xìnxī",kr:"정보",lv:4,tp:"명사",ex:[{cn:"发信息。",py:"Fā xìnxī.",kr:"메시지를 보내다."}]},
{hz:"网络",py:"wǎngluò",kr:"네트워크, 인터넷",lv:4,tp:"명사",ex:[{cn:"网络时代。",py:"Wǎngluò shídài.",kr:"인터넷 시대."}]},
{hz:"由于",py:"yóuyú",kr:"~로 인해",lv:4,tp:"전치사",ex:[{cn:"由于天气。",py:"Yóuyú tiānqì.",kr:"날씨로 인해."}]},
{hz:"关于",py:"guānyú",kr:"~에 관하여",lv:4,tp:"전치사",ex:[{cn:"关于学习。",py:"Guānyú xuéxí.",kr:"학습에 관하여."}]},
{hz:"随着",py:"suízhe",kr:"~에 따라",lv:4,tp:"전치사",ex:[{cn:"随着时间。",py:"Suízhe shíjiān.",kr:"시간에 따라."}]},
{hz:"往往",py:"wǎngwǎng",kr:"대개",lv:4,tp:"부사",ex:[{cn:"他往往迟到。",py:"Tā wǎngwǎng chídào.",kr:"그는 대개 늦는다."}]},
{hz:"逐渐",py:"zhújiàn",kr:"점차",lv:4,tp:"부사",ex:[{cn:"逐渐好了。",py:"Zhújiàn hǎo le.",kr:"점차 좋아졌다."}]},
{hz:"目前",py:"mùqián",kr:"현재",lv:4,tp:"명사",ex:[{cn:"目前的情况。",py:"Mùqián de qíngkuàng.",kr:"현재의 상황."}]},
{hz:"将来",py:"jiānglái",kr:"장래, 미래",lv:4,tp:"명사",ex:[{cn:"将来的计划。",py:"Jiānglái de jìhuà.",kr:"미래의 계획."}]},
{hz:"总结",py:"zǒngjié",kr:"종합, 결론짓다",lv:4,tp:"동사/명사",ex:[{cn:"总结经验。",py:"Zǒngjié jīngyàn.",kr:"경험을 종합하다."}]},
{hz:"尊重",py:"zūnzhòng",kr:"존중하다",lv:4,tp:"동사",ex:[{cn:"尊重别人。",py:"Zūnzhòng biérén.",kr:"다른 사람을 존중하다."}]},
{hz:"沟通",py:"gōutōng",kr:"소통하다",lv:4,tp:"동사",ex:[{cn:"好好沟通。",py:"Hǎohǎo gōutōng.",kr:"잘 소통하다."}]},
{hz:"竞争",py:"jìngzhēng",kr:"경쟁하다",lv:4,tp:"동사/명사",ex:[{cn:"竞争激烈。",py:"Jìngzhēng jīliè.",kr:"경쟁이 치열하다."}]},
{hz:"合作",py:"hézuò",kr:"협력하다",lv:4,tp:"동사",ex:[{cn:"合作愉快。",py:"Hézuò yúkuài.",kr:"즐거운 협력."}]},
{hz:"毕业",py:"bìyè",kr:"졸업하다",lv:4,tp:"동사",ex:[{cn:"大学毕业。",py:"Dàxué bìyè.",kr:"대학을 졸업하다."}]},
{hz:"丰富",py:"fēngfù",kr:"풍부하다",lv:4,tp:"형용사",ex:[{cn:"内容丰富。",py:"Nèiróng fēngfù.",kr:"내용이 풍부하다."}]},
{hz:"复杂",py:"fùzá",kr:"복잡하다",lv:4,tp:"형용사",ex:[{cn:"很复杂。",py:"Hěn fùzá.",kr:"매우 복잡하다."}]},
{hz:"优秀",py:"yōuxiù",kr:"우수하다",lv:4,tp:"형용사",ex:[{cn:"优秀学生。",py:"Yōuxiù xuéshēng.",kr:"우수한 학생."}]},
{hz:"专业",py:"zhuānyè",kr:"전문적이다, 전공",lv:4,tp:"형용사/명사",ex:[{cn:"很专业。",py:"Hěn zhuānyè.",kr:"매우 전문적이다."}]},
{hz:"职业",py:"zhíyè",kr:"직업",lv:4,tp:"명사",ex:[{cn:"什么职业？",py:"Shénme zhíyè?",kr:"무슨 직업이야?"}]},
{hz:"工资",py:"gōngzī",kr:"월급",lv:4,tp:"명사",ex:[{cn:"工资很高。",py:"Gōngzī hěn gāo.",kr:"월급이 높다."}]},
{hz:"签证",py:"qiānzhèng",kr:"비자",lv:4,tp:"명사",ex:[{cn:"办签证。",py:"Bàn qiānzhèng.",kr:"비자를 발급받다."}]},
{hz:"经历",py:"jīnglì",kr:"경력, 경험",lv:4,tp:"명사/동사",ex:[{cn:"丰富的经历。",py:"Fēngfù de jīnglì.",kr:"풍부한 경력."}]},

// ===== HSK 5 (1300 words - representative selection) =====
{hz:"本质",py:"běnzhì",kr:"본질",lv:5,tp:"명사",ex:[{cn:"问题的本质。",py:"Wèntí de běnzhì.",kr:"문제의 본질."}]},
{hz:"概念",py:"gàiniàn",kr:"개념",lv:5,tp:"명사",ex:[{cn:"新概念。",py:"Xīn gàiniàn.",kr:"새로운 개념."}]},
{hz:"领域",py:"lǐngyù",kr:"영역, 분야",lv:5,tp:"명사",ex:[{cn:"各个领域。",py:"Gè gè lǐngyù.",kr:"각 분야."}]},
{hz:"趋势",py:"qūshì",kr:"추세",lv:5,tp:"명사",ex:[{cn:"发展趋势。",py:"Fāzhǎn qūshì.",kr:"발전 추세."}]},
{hz:"现象",py:"xiànxiàng",kr:"현상",lv:5,tp:"명사",ex:[{cn:"社会现象。",py:"Shèhuì xiànxiàng.",kr:"사회 현상."}]},
{hz:"结构",py:"jiégòu",kr:"구조",lv:5,tp:"명사",ex:[{cn:"经济结构。",py:"Jīngjì jiégòu.",kr:"경제 구조."}]},
{hz:"制度",py:"zhìdù",kr:"제도",lv:5,tp:"명사",ex:[{cn:"教育制度。",py:"Jiàoyù zhìdù.",kr:"교육 제도."}]},
{hz:"原则",py:"yuánzé",kr:"원칙",lv:5,tp:"명사",ex:[{cn:"基本原则。",py:"Jīběn yuánzé.",kr:"기본 원칙."}]},
{hz:"观念",py:"guānniàn",kr:"관념",lv:5,tp:"명사",ex:[{cn:"传统观念。",py:"Chuántǒng guānniàn.",kr:"전통적 관념."}]},
{hz:"价值",py:"jiàzhí",kr:"가치",lv:5,tp:"명사",ex:[{cn:"有价值。",py:"Yǒu jiàzhí.",kr:"가치가 있다."}]},
{hz:"矛盾",py:"máodùn",kr:"모순",lv:5,tp:"명사",ex:[{cn:"存在矛盾。",py:"Cúnzài máodùn.",kr:"모순이 존재한다."}]},
{hz:"现实",py:"xiànshí",kr:"현실",lv:5,tp:"명사",ex:[{cn:"面对现实。",py:"Miànduì xiànshí.",kr:"현실에 직면하다."}]},
{hz:"促进",py:"cùjìn",kr:"촉진하다",lv:5,tp:"동사",ex:[{cn:"促进发展。",py:"Cùjìn fāzhǎn.",kr:"발전을 촉진하다."}]},
{hz:"维持",py:"wéichí",kr:"유지하다",lv:5,tp:"동사",ex:[{cn:"维持秩序。",py:"Wéichí zhìxù.",kr:"질서를 유지하다."}]},
{hz:"克服",py:"kèfú",kr:"극복하다",lv:5,tp:"동사",ex:[{cn:"克服困难。",py:"Kèfú kùnnán.",kr:"어려움을 극복하다."}]},
{hz:"掌握",py:"zhǎngwò",kr:"장악하다, 파악하다",lv:5,tp:"동사",ex:[{cn:"掌握知识。",py:"Zhǎngwò zhīshì.",kr:"지식을 파악하다."}]},
{hz:"构成",py:"gòuchéng",kr:"구성하다",lv:5,tp:"동사",ex:[{cn:"构成威胁。",py:"Gòuchéng wēixié.",kr:"위협을 구성하다."}]},
{hz:"体现",py:"tǐxiàn",kr:"체현하다",lv:5,tp:"동사",ex:[{cn:"体现精神。",py:"Tǐxiàn jīngshén.",kr:"정신을 나타내다."}]},
{hz:"强调",py:"qiángdiào",kr:"강조하다",lv:5,tp:"동사",ex:[{cn:"强调重要性。",py:"Qiángdiào zhòngyàoxìng.",kr:"중요성을 강조하다."}]},
{hz:"采取",py:"cǎiqǔ",kr:"취하다, 채택하다",lv:5,tp:"동사",ex:[{cn:"采取措施。",py:"Cǎiqǔ cuòshī.",kr:"조치를 취하다."}]},
{hz:"承担",py:"chéngdān",kr:"맡다, 부담하다",lv:5,tp:"동사",ex:[{cn:"承担责任。",py:"Chéngdān zérèn.",kr:"책임을 맡다."}]},
{hz:"面临",py:"miànlín",kr:"직면하다",lv:5,tp:"동사",ex:[{cn:"面临困难。",py:"Miànlín kùnnán.",kr:"어려움에 직면하다."}]},
{hz:"反复",py:"fǎnfù",kr:"반복하다",lv:5,tp:"부사/동사",ex:[{cn:"反复练习。",py:"Fǎnfù liànxí.",kr:"반복 연습하다."}]},
{hz:"充分",py:"chōngfèn",kr:"충분하다",lv:5,tp:"형용사",ex:[{cn:"充分准备。",py:"Chōngfèn zhǔnbèi.",kr:"충분히 준비하다."}]},
{hz:"显著",py:"xiǎnzhù",kr:"현저하다",lv:5,tp:"형용사",ex:[{cn:"效果显著。",py:"Xiàoguǒ xiǎnzhù.",kr:"효과가 현저하다."}]},
{hz:"深刻",py:"shēnkè",kr:"심각하다, 깊다",lv:5,tp:"형용사",ex:[{cn:"印象深刻。",py:"Yìnxiàng shēnkè.",kr:"인상이 깊다."}]},
{hz:"独立",py:"dúlì",kr:"독립적이다",lv:5,tp:"형용사",ex:[{cn:"独立思考。",py:"Dúlì sīkǎo.",kr:"독립적으로 사고하다."}]},
{hz:"客观",py:"kèguān",kr:"객관적이다",lv:5,tp:"형용사",ex:[{cn:"客观评价。",py:"Kèguān píngjià.",kr:"객관적으로 평가하다."}]},
{hz:"灵活",py:"línghuó",kr:"유연하다",lv:5,tp:"형용사",ex:[{cn:"方法灵活。",py:"Fāngfǎ línghuó.",kr:"방법이 유연하다."}]},
{hz:"普遍",py:"pǔbiàn",kr:"보편적이다",lv:5,tp:"형용사",ex:[{cn:"很普遍。",py:"Hěn pǔbiàn.",kr:"매우 보편적이다."}]},
{hz:"传统",py:"chuántǒng",kr:"전통",lv:5,tp:"명사/형용사",ex:[{cn:"传统文化。",py:"Chuántǒng wénhuà.",kr:"전통 문화."}]},
{hz:"精神",py:"jīngshén",kr:"정신",lv:5,tp:"명사",ex:[{cn:"精神力量。",py:"Jīngshén lìliàng.",kr:"정신적 힘."}]},
{hz:"资源",py:"zīyuán",kr:"자원",lv:5,tp:"명사",ex:[{cn:"自然资源。",py:"Zìrán zīyuán.",kr:"자연 자원."}]},
{hz:"技术",py:"jìshù",kr:"기술",lv:5,tp:"명사",ex:[{cn:"先进技术。",py:"Xiānjìn jìshù.",kr:"선진 기술."}]},
{hz:"措施",py:"cuòshī",kr:"조치",lv:5,tp:"명사",ex:[{cn:"采取措施。",py:"Cǎiqǔ cuòshī.",kr:"조치를 취하다."}]},
{hz:"角度",py:"jiǎodù",kr:"각도, 관점",lv:5,tp:"명사",ex:[{cn:"从这个角度。",py:"Cóng zhège jiǎodù.",kr:"이 관점에서."}]},
{hz:"素质",py:"sùzhì",kr:"자질, 소양",lv:5,tp:"명사",ex:[{cn:"提高素质。",py:"Tígāo sùzhì.",kr:"자질을 높이다."}]},
{hz:"规模",py:"guīmó",kr:"규모",lv:5,tp:"명사",ex:[{cn:"大规模。",py:"Dà guīmó.",kr:"대규모."}]},
{hz:"范围",py:"fànwéi",kr:"범위",lv:5,tp:"명사",ex:[{cn:"范围很广。",py:"Fànwéi hěn guǎng.",kr:"범위가 넓다."}]},
{hz:"阶段",py:"jiēduàn",kr:"단계",lv:5,tp:"명사",ex:[{cn:"发展阶段。",py:"Fāzhǎn jiēduàn.",kr:"발전 단계."}]},
{hz:"在于",py:"zàiyú",kr:"~에 있다",lv:5,tp:"동사",ex:[{cn:"关键在于努力。",py:"Guānjiàn zàiyú nǔlì.",kr:"핵심은 노력에 있다."}]},
{hz:"意味着",py:"yìwèizhe",kr:"~을 의미하다",lv:5,tp:"동사",ex:[{cn:"这意味着成功。",py:"Zhè yìwèizhe chénggōng.",kr:"이것은 성공을 의미한다."}]},
{hz:"属于",py:"shǔyú",kr:"~에 속하다",lv:5,tp:"동사",ex:[{cn:"属于我的。",py:"Shǔyú wǒ de.",kr:"나에게 속하다."}]},
{hz:"适应",py:"shìyìng",kr:"적응하다",lv:5,tp:"동사",ex:[{cn:"适应环境。",py:"Shìyìng huánjìng.",kr:"환경에 적응하다."}]},
{hz:"形成",py:"xíngchéng",kr:"형성하다",lv:5,tp:"동사",ex:[{cn:"形成习惯。",py:"Xíngchéng xíguàn.",kr:"습관을 형성하다."}]},
{hz:"推动",py:"tuīdòng",kr:"추진하다",lv:5,tp:"동사",ex:[{cn:"推动发展。",py:"Tuīdòng fāzhǎn.",kr:"발전을 추진하다."}]},
{hz:"针对",py:"zhēnduì",kr:"~에 대해",lv:5,tp:"전치사",ex:[{cn:"针对问题。",py:"Zhēnduì wèntí.",kr:"문제에 대해."}]},
{hz:"从而",py:"cóng'ér",kr:"그리하여",lv:5,tp:"접속사",ex:[{cn:"从而成功。",py:"Cóng'ér chénggōng.",kr:"그리하여 성공하다."}]},
{hz:"不仅",py:"bùjǐn",kr:"~뿐만 아니라",lv:5,tp:"접속사",ex:[{cn:"不仅学习好。",py:"Bùjǐn xuéxí hǎo.",kr:"학습뿐만 아니라."}]},
{hz:"反而",py:"fǎn'ér",kr:"오히려",lv:5,tp:"부사",ex:[{cn:"反而更好。",py:"Fǎn'ér gèng hǎo.",kr:"오히려 더 좋다."}]},
{hz:"缺乏",py:"quēfá",kr:"결핍되다",lv:5,tp:"동사",ex:[{cn:"缺乏经验。",py:"Quēfá jīngyàn.",kr:"경험이 부족하다."}]},
{hz:"具备",py:"jùbèi",kr:"구비하다",lv:5,tp:"동사",ex:[{cn:"具备条件。",py:"Jùbèi tiáojiàn.",kr:"조건을 갖추다."}]},
{hz:"依然",py:"yīrán",kr:"여전히",lv:5,tp:"부사",ex:[{cn:"依然存在。",py:"Yīrán cúnzài.",kr:"여전히 존재한다."}]},
{hz:"居然",py:"jūrán",kr:"뜻밖에",lv:5,tp:"부사",ex:[{cn:"居然成功了。",py:"Jūrán chénggōng le.",kr:"뜻밖에 성공했다."}]},
{hz:"竟然",py:"jìngrán",kr:"뜻밖에도",lv:5,tp:"부사",ex:[{cn:"竟然来了。",py:"Jìngrán lái le.",kr:"뜻밖에도 왔다."}]},
{hz:"究竟",py:"jiūjìng",kr:"도대체",lv:5,tp:"부사",ex:[{cn:"究竟是谁？",py:"Jiūjìng shì shéi?",kr:"도대체 누구야?"}]},
{hz:"确实",py:"quèshí",kr:"확실히",lv:5,tp:"부사",ex:[{cn:"确实很好。",py:"Quèshí hěn hǎo.",kr:"확실히 좋다."}]},
{hz:"恰好",py:"qiàhǎo",kr:"마침",lv:5,tp:"부사",ex:[{cn:"恰好遇到。",py:"Qiàhǎo yù dào.",kr:"마침 만났다."}]},
{hz:"至少",py:"zhìshǎo",kr:"적어도",lv:5,tp:"부사",ex:[{cn:"至少三个。",py:"Zhìshǎo sān gè.",kr:"적어도 세 개."}]},
{hz:"至今",py:"zhìjīn",kr:"지금까지",lv:5,tp:"부사",ex:[{cn:"至今未解决。",py:"Zhìjīn wèi jiějué.",kr:"지금까지 해결되지 않았다."}]},
{hz:"难免",py:"nánmiǎn",kr:"피할 수 없다",lv:5,tp:"부사",ex:[{cn:"难免出错。",py:"Nánmiǎn chū cuò.",kr:"실수는 피할 수 없다."}]},
{hz:"往往",py:"wǎngwǎng",kr:"왕왕, 대개",lv:5,tp:"부사",ex:[{cn:"往往如此。",py:"Wǎngwǎng rúcǐ.",kr:"대개 이렇다."}]},
{hz:"繁荣",py:"fánróng",kr:"번영하다",lv:5,tp:"형용사",ex:[{cn:"经济繁荣。",py:"Jīngjì fánróng.",kr:"경제가 번영하다."}]},
{hz:"稳定",py:"wěndìng",kr:"안정적이다",lv:5,tp:"형용사",ex:[{cn:"社会稳定。",py:"Shèhuì wěndìng.",kr:"사회가 안정적이다."}]},
{hz:"透明",py:"tòumíng",kr:"투명하다",lv:5,tp:"형용사",ex:[{cn:"透明的水。",py:"Tòumíng de shuǐ.",kr:"투명한 물."}]},
{hz:"微妙",py:"wēimiào",kr:"미묘하다",lv:5,tp:"형용사",ex:[{cn:"关系微妙。",py:"Guānxì wēimiào.",kr:"관계가 미묘하다."}]},
{hz:"彻底",py:"chèdǐ",kr:"철저하다",lv:5,tp:"형용사",ex:[{cn:"彻底解决。",py:"Chèdǐ jiějué.",kr:"철저히 해결하다."}]},
{hz:"频繁",py:"pínfán",kr:"빈번하다",lv:5,tp:"형용사",ex:[{cn:"交流频繁。",py:"Jiāoliú pínfán.",kr:"교류가 빈번하다."}]},
{hz:"紧迫",py:"jǐnpò",kr:"긴박하다",lv:5,tp:"형용사",ex:[{cn:"形势紧迫。",py:"Xíngshì jǐnpò.",kr:"형세가 긴박하다."}]},
{hz:"对策",py:"duìcè",kr:"대책",lv:5,tp:"명사",ex:[{cn:"制定对策。",py:"Zhìdìng duìcè.",kr:"대책을 세우다."}]},
{hz:"前途",py:"qiántú",kr:"전도, 미래",lv:5,tp:"명사",ex:[{cn:"前途光明。",py:"Qiántú guāngmíng.",kr:"전도가 밝다."}]},
{hz:"动力",py:"dònglì",kr:"동력",lv:5,tp:"명사",ex:[{cn:"发展动力。",py:"Fāzhǎn dònglì.",kr:"발전의 동력."}]},
{hz:"比例",py:"bǐlì",kr:"비율",lv:5,tp:"명사",ex:[{cn:"比例很大。",py:"Bǐlì hěn dà.",kr:"비율이 크다."}]},
{hz:"因素",py:"yīnsù",kr:"요소",lv:5,tp:"명사",ex:[{cn:"重要因素。",py:"Zhòngyào yīnsù.",kr:"중요한 요소."}]},
{hz:"特征",py:"tèzhēng",kr:"특징",lv:5,tp:"명사",ex:[{cn:"主要特征。",py:"Zhǔyào tèzhēng.",kr:"주요 특징."}]},
{hz:"程度",py:"chéngdù",kr:"정도",lv:5,tp:"명사",ex:[{cn:"在一定程度上。",py:"Zài yīdìng chéngdù shàng.",kr:"어느 정도."}]},
{hz:"立场",py:"lìchǎng",kr:"입장",lv:5,tp:"명사",ex:[{cn:"不同立场。",py:"Bùtóng lìchǎng.",kr:"다른 입장."}]},
{hz:"前提",py:"qiántí",kr:"전제",lv:5,tp:"명사",ex:[{cn:"前提条件。",py:"Qiántí tiáojiàn.",kr:"전제 조건."}]},
{hz:"背景",py:"bèijǐng",kr:"배경",lv:5,tp:"명사",ex:[{cn:"历史背景。",py:"Lìshǐ bèijǐng.",kr:"역사적 배경."}]},
{hz:"优势",py:"yōushì",kr:"우세, 장점",lv:5,tp:"명사",ex:[{cn:"有优势。",py:"Yǒu yōushì.",kr:"장점이 있다."}]},
{hz:"挑战",py:"tiǎozhàn",kr:"도전",lv:5,tp:"명사/동사",ex:[{cn:"面对挑战。",py:"Miànduì tiǎozhàn.",kr:"도전에 직면하다."}]},
{hz:"利益",py:"lìyì",kr:"이익",lv:5,tp:"명사",ex:[{cn:"共同利益。",py:"Gòngtóng lìyì.",kr:"공동 이익."}]},
{hz:"规律",py:"guīlǜ",kr:"규칙, 법칙",lv:5,tp:"명사",ex:[{cn:"自然规律。",py:"Zìrán guīlǜ.",kr:"자연 법칙."}]},
{hz:"意识",py:"yìshí",kr:"의식",lv:5,tp:"명사",ex:[{cn:"意识到。",py:"Yìshí dào.",kr:"의식하다."}]},
{hz:"战略",py:"zhànlüè",kr:"전략",lv:5,tp:"명사",ex:[{cn:"发展战略。",py:"Fāzhǎn zhànlüè.",kr:"발전 전략."}]},
{hz:"机制",py:"jīzhì",kr:"메커니즘",lv:5,tp:"명사",ex:[{cn:"市场机制。",py:"Shìchǎng jīzhì.",kr:"시장 메커니즘."}]},
{hz:"贡献",py:"gòngxiàn",kr:"공헌",lv:5,tp:"명사/동사",ex:[{cn:"做贡献。",py:"Zuò gòngxiàn.",kr:"공헌하다."}]},
{hz:"成就",py:"chéngjiù",kr:"성취",lv:5,tp:"명사",ex:[{cn:"取得成就。",py:"Qǔdé chéngjiù.",kr:"성취를 이루다."}]},
{hz:"启发",py:"qǐfā",kr:"계발하다",lv:5,tp:"동사",ex:[{cn:"启发思考。",py:"Qǐfā sīkǎo.",kr:"사고를 계발하다."}]},
{hz:"拓展",py:"tuòzhǎn",kr:"확장하다",lv:5,tp:"동사",ex:[{cn:"拓展市场。",py:"Tuòzhǎn shìchǎng.",kr:"시장을 확장하다."}]},
{hz:"呈现",py:"chéngxiàn",kr:"나타내다",lv:5,tp:"동사",ex:[{cn:"呈现出来。",py:"Chéngxiàn chūlái.",kr:"나타나다."}]},
{hz:"涉及",py:"shèjí",kr:"관련되다",lv:5,tp:"동사",ex:[{cn:"涉及很多。",py:"Shèjí hěn duō.",kr:"많이 관련되다."}]},
{hz:"指出",py:"zhǐchū",kr:"지적하다",lv:5,tp:"동사",ex:[{cn:"专家指出。",py:"Zhuānjiā zhǐchū.",kr:"전문가가 지적하다."}]},
{hz:"表明",py:"biǎomíng",kr:"밝히다",lv:5,tp:"동사",ex:[{cn:"数据表明。",py:"Shùjù biǎomíng.",kr:"데이터가 보여주다."}]},
{hz:"发挥",py:"fāhuī",kr:"발휘하다",lv:5,tp:"동사",ex:[{cn:"发挥作用。",py:"Fāhuī zuòyòng.",kr:"역할을 발휘하다."}]},
{hz:"证实",py:"zhèngshí",kr:"입증하다",lv:5,tp:"동사",ex:[{cn:"已被证实。",py:"Yǐ bèi zhèngshí.",kr:"이미 입증되었다."}]},
{hz:"评估",py:"pínggū",kr:"평가하다",lv:5,tp:"동사",ex:[{cn:"评估效果。",py:"Pínggū xiàoguǒ.",kr:"효과를 평가하다."}]},
{hz:"预测",py:"yùcè",kr:"예측하다",lv:5,tp:"동사",ex:[{cn:"预测未来。",py:"Yùcè wèilái.",kr:"미래를 예측하다."}]},
{hz:"激发",py:"jīfā",kr:"자극하다",lv:5,tp:"동사",ex:[{cn:"激发兴趣。",py:"Jīfā xìngqù.",kr:"흥미를 자극하다."}]},
{hz:"呼吁",py:"hūyù",kr:"호소하다",lv:5,tp:"동사",ex:[{cn:"呼吁和平。",py:"Hūyù hépíng.",kr:"평화를 호소하다."}]},
{hz:"融合",py:"rónghé",kr:"융합하다",lv:5,tp:"동사",ex:[{cn:"文化融合。",py:"Wénhuà rónghé.",kr:"문화 융합."}]},
{hz:"弥补",py:"míbǔ",kr:"보충하다",lv:5,tp:"동사",ex:[{cn:"弥补不足。",py:"Míbǔ bùzú.",kr:"부족함을 보충하다."}]},
{hz:"遵循",py:"zūnxún",kr:"따르다",lv:5,tp:"동사",ex:[{cn:"遵循规律。",py:"Zūnxún guīlǜ.",kr:"법칙을 따르다."}]},
{hz:"抵达",py:"dǐdá",kr:"도달하다",lv:5,tp:"동사",ex:[{cn:"抵达目的地。",py:"Dǐdá mùdìdì.",kr:"목적지에 도달하다."}]},
{hz:"妨碍",py:"fáng'ài",kr:"방해하다",lv:5,tp:"동사",ex:[{cn:"妨碍发展。",py:"Fáng'ài fāzhǎn.",kr:"발전을 방해하다."}]},
{hz:"崇拜",py:"chóngbài",kr:"숭배하다",lv:5,tp:"동사",ex:[{cn:"崇拜英雄。",py:"Chóngbài yīngxióng.",kr:"영웅을 숭배하다."}]},
{hz:"抱怨",py:"bàoyuàn",kr:"불평하다",lv:5,tp:"동사",ex:[{cn:"不要抱怨。",py:"Búyào bàoyuàn.",kr:"불평하지 마."}]},
{hz:"辩论",py:"biànlùn",kr:"변론하다",lv:5,tp:"동사",ex:[{cn:"辩论会。",py:"Biànlùn huì.",kr:"토론회."}]},
{hz:"淘汰",py:"táotài",kr:"도태시키다",lv:5,tp:"동사",ex:[{cn:"被淘汰。",py:"Bèi táotài.",kr:"도태되다."}]},
{hz:"协调",py:"xiétiáo",kr:"조율하다",lv:5,tp:"동사",ex:[{cn:"协调关系。",py:"Xiétiáo guānxì.",kr:"관계를 조율하다."}]},
{hz:"潜力",py:"qiánlì",kr:"잠재력",lv:5,tp:"명사",ex:[{cn:"有潜力。",py:"Yǒu qiánlì.",kr:"잠재력이 있다."}]},
{hz:"智慧",py:"zhìhuì",kr:"지혜",lv:5,tp:"명사",ex:[{cn:"人类智慧。",py:"Rénlèi zhìhuì.",kr:"인류의 지혜."}]},
{hz:"命运",py:"mìngyùn",kr:"운명",lv:5,tp:"명사",ex:[{cn:"改变命运。",py:"Gǎibiàn mìngyùn.",kr:"운명을 바꾸다."}]},
{hz:"风险",py:"fēngxiǎn",kr:"위험, 리스크",lv:5,tp:"명사",ex:[{cn:"风险很大。",py:"Fēngxiǎn hěn dà.",kr:"리스크가 크다."}]},
{hz:"效率",py:"xiàolǜ",kr:"효율",lv:5,tp:"명사",ex:[{cn:"提高效率。",py:"Tígāo xiàolǜ.",kr:"효율을 높이다."}]},
{hz:"核心",py:"héxīn",kr:"핵심",lv:5,tp:"명사",ex:[{cn:"核心问题。",py:"Héxīn wèntí.",kr:"핵심 문제."}]},
{hz:"根源",py:"gēnyuán",kr:"근원",lv:5,tp:"명사",ex:[{cn:"问题的根源。",py:"Wèntí de gēnyuán.",kr:"문제의 근원."}]},
{hz:"途径",py:"tújìng",kr:"방법, 경로",lv:5,tp:"명사",ex:[{cn:"重要途径。",py:"Zhòngyào tújìng.",kr:"중요한 경로."}]},
];
